### ISSUE TITLE
NoOne - use `safeApprove` instead `approve`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#10]
NoOne

medium

# use `safeApprove` instead `approve`

## Impact
Tokens not compliant with the ERC20 specification could return false from the `approve` function call to indicate the approval fails, while the calling contract would not notice the failure if the return value is not checked.
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L762
## Tool used

Manual Review

## Recommendation
Use the safeApprove function instead, which reverts the transaction with a proper error message when the return value of approve is false.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because only whitelisted ERC20 standard tokens can work with the codebase
