### ISSUE TITLE
0xBhumii - `pointsPerBlock` Can Be Set to Zero During Initialization

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#104]
0xBhumii

medium

# `pointsPerBlock` Can Be Set to Zero During Initialization

## Summary
The `pointsPerBlock` variable can be set to zero during the `initialization` of the contract, which would effectively halt the distribution of rewards.
## Vulnerability Detail
During the `initialize` function, there is no check to ensure that the `_pointsPerBlock` parameter is greater than zero. This could result in the `pointsPerBlock` being set to zero, which would stop reward distribution and affect the entire farming mechanism. although it can be changed later using 'setPointsPerBlock' function, it will cost extra gas , so its better to have a validation for `pointsPerBlock` during initialization itself
## Impact
If `pointsPerBlock` is set to `zero`, no rewards will be distributed to users, rendering the farming functionality ineffective and potentially causing significant financial loss and user dissatisfaction.
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L113
## Tool used

Manual Review

## Recommendation
Add a check to ensure that `_pointsPerBlock` is greater than `zero` during the initialization process.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because of zero value validation
