### ISSUE TITLE
VAD37 - Admin can reset `endBlock` to zero even after farming has ended

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#109]
VAD37

medium

# Admin can reset `endBlock` to zero even after farming has ended

## Summary

There is missing validation check flaw from `setEndBlock()` function in `SophonFarming.sol` that allows the admin to reset the endBlock to zero even after farming has ended.
This action bypasses the intended checks and break intended behavior.

## Vulnerability Detail

Normally, the owner can call `setEndBlock()` to move the `endBlock` forward before farming ends.
The function is designed to revert if farming has already ended, if the new `endBlock` is smaller than the current block, or if it is smaller than the `startBlock`, as a safety check. The relevant code is shown below:

```solidity
    function setEndBlock(uint256 _endBlock, uint256 _withdrawalBlocks) public onlyOwner {
        uint256 _endBlockForWithdrawals;
        if (_endBlock != 0) {
            if (_endBlock <= startBlock || getBlockNumber() > _endBlock) {//@note can still set endblock same as current block
                revert InvalidEndBlock();
            }
            if (isFarmingEnded()) {//@skip if endblock ==0
                revert FarmingIsEnded();
            }
            _endBlockForWithdrawals = _endBlock + _withdrawalBlocks;
        } else {
            // withdrawal blocks needs an endBlock
            _endBlockForWithdrawals = 0;
        }
        massUpdatePools();
        endBlock = _endBlock;//@audit M owner can set end block to 0 allowing emergency withdrawal of everyone and reset to new endblock. bypass isFarmingEnded
        endBlockForWithdrawals = _endBlockForWithdrawals;//@note withdrawal block can be same as endBlock.
    }
```

However, the owner can also call `setEndBlock()` to reset `endBlock` to zero, effectively bypassing the `isFarmingEnded()` check.
This allows users to withdraw or deposit after farming has ended, which is not the intended behavior.
After farming ends, the owner typically moves all funds to another chain for farming and rewarding users later.
Thus, there are no funds to withdraw unless new deposits are made after farming ends.

## Impact

The owner can unexpectedly reset `endBlock` to zero after farming has ended.
This allows users to withdraw or deposit after farming has ended, which is not the intended behavior and could lead to financial inconsistencies and security risks.

## Code Snippet

<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L288-L305>

## Tool used

Manual Review

## Recommendation

Prevent `endBlock` from reset to zero after farming ended.

**Comment by sherlock-admin4** [comment]
4 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the protocol team might want to free up withdrawal period that will otherwise have users' deposit amount stuck while preventing point accumulation. Users purchasing boost will be a waste though at this point

**0xmystery** commented:
>  invalid because the protocol team might want to free up withdrawal period that will otherwise have users' deposit amount stuck while preventing point accumulation. Users purchasing boost will be a waste though at this point

**0xmystery** commented:
>  invalid because the protocol team might want to free up withdrawal period that will otherwise have users' deposit amount stuck while preventing point accumulation. Users purchasing boost will be a waste though at this point

**0xmystery** commented:
>  invalid because the protocol team might want to free up withdrawal period that will otherwise have users' deposit amount stuck while preventing point accumulation. Users purchasing boost will be a waste though at this point
