### ISSUE TITLE
VAD37 - Unfair rewards distribution due to lack of end accrued date in `getPendingPoints()`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#110]
VAD37

high

# Unfair rewards distribution due to lack of end accrued date in `getPendingPoints()`

## Summary

The `getPendingPoints()` function in `SophonFarming.sol` calculates user rewards without considering an end date, allowing users to accrue points beyond the farming period.
Resulting in unfair rewards distribution if rewards are sent over multiple periods.

## Vulnerability Detail

When users deposit or withdraw, their accrued points and rewards are calculated and cached. [Here1](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L590-L596), [Here2](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L620-L622).

The admin will later call `getPendingPoints()` or `getOptimizedUserInfo()` after bridging tokens to get the user's accrued points and rewards up to the current block.
This result is used to determine the rewards to be sent to the user.
<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L899-L915>

Since user rewards do not have a cap, `getPendingPoints()` will continue to increase over time.
If the owner sends rewards over multiple periods, users will receive inconsistent rewards because the rewards calculation changes with each new timestamp, leading to unfair distribution.

## Impact

Relying on `getPendingPoints()` for user rewards results in unfair distribution due to changing timestamps.

## Code Snippet

<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L358-L385>

## Tool used

Manual Review

## Recommendation

Consider using a withdrawal date as a cut-off point, to ensure consistent rewards distribution.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because this will be circumvated by _to = Math.min(_to, _endBlock) in _getBlockMultiplier()
