### ISSUE TITLE
VAD37 - If `SophonFarming.sol` have some spare DAI token. Then user can permanently loss ETH when depositing into sDAI pool

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#112]
VAD37

medium

# If `SophonFarming.sol` have some spare DAI token. Then user can permanently loss ETH when depositing into sDAI pool

## Summary

`depositEth()` and `depositWeth()` does not invalidate transaction if `PredefinedPool` is `PredefinedPool.sDAI`.

If some random user transfer like 10 DAI token to `SophonFarming.sol`.
And another user deposit 10 ETH to sDAI pool. The transaction will pass and the user will get 10 sDAI token in pool and lost 10 ETH.

And 10 ETH token will permanently locked in the contract with no admin rescue function.

## Vulnerability Detail

The `depositEth()` and `depositWeth()` functions lack an else case to revert transactions for irrelevant cases, such as when the predefined pool is sDAI:
<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L504-L540>

Typically, if a user deposits ETH into the sDAI pool, the transaction should revert when attempting to wrap DAI to sDAI:
[Reference Here](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L554)

However, if a malicious user transfers some cheap DAI tokens to the contract and another user deposits ETH into the sDAI pool, the `_daiTOsDai()` call will succeed, and the transaction will pass.
The user will receive sDAI tokens in the pool but lose their ETH tokens, which will be permanently locked in the contract without any admin rescue function.

## Impact

There is a small chance of unexpected transaction behavior resulting in the permanent loss of ETH tokens.

## Code Snippet

<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L504-L540>

## Tool used

Manual Review

## Recommendation

Include else case in `depositEth()` and `depositWeth()` function to revert transaction if `PredefinedPool` is `PredefinedPool.sDAI`

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because user input validation to prevent user mistakes is not considered a valid issue. Additionally, the likelihood of the scenario happening is extremely low

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/f0b82fd83a5d85eb8dc7ba2bbce2d49fefb326a4

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
