### ISSUE TITLE
VAD37 - Admin update `boosterMultiplier` cause unfair reward distribution between old and new booster deposit

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#113]
VAD37

medium

# Admin update `boosterMultiplier` cause unfair reward distribution between old and new booster deposit

## Summary

The `boosterMultiplier` is used to calculate user rewards.
If the admin updates this multiplier to a higher value at a later date, users who have already locked deposits with the old booster rate will receive fewer rewards compared to new users with new deposits and the updated booster rate.
This creates an unfair reward distribution between users before and after the update.

## Vulnerability Detail

The admin can update the booster rate anytime before farming ends
<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L323-L332>

When a user deposits or increases their booster, the multiplier is applied once and the deposit is locked.
<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L608-L612>

```solidity
        // apply the boost multiplier
        _boostAmount = _boostAmount * boosterMultiplier / 1e18; //@note boost is just a portion of deposit multiplied to give extra rewards
        //@audit M boosterMultiplier config changed later by admin will affect previous and future deposit.
        user.boostAmount = user.boostAmount + _boostAmount;
        pool.boostAmount = pool.boostAmount + _boostAmount;//@note pool.boost = sum (user.boost)
```

Once the booster is added, users cannot decrease or remove it. It is locked permanently.

Rewards distribution later [here](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L380-L384) will smaller for user with old booster rate.

Because their `user.amount` is smaller due to less booster multiplier

## Impact

If the admin updates the `boosterMultiplier` to a higher value later, all users who have already locked deposits with the old booster rate will receive fewer rewards compared to new users with new deposits and the updated booster rate.

## Code Snippet

<https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L608-L612>

## Tool used

Manual Review

## Recommendation

Allow users to update their booster rate to the new rate or prevent updates to the booster rate after farming has started to ensure fair reward distribution.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because an admin action can break certain assumptions about the functioning of the code, presumably to encourage purchase of boost for the final run
