### ISSUE TITLE
0xBhumii - Ensure a Minimum Difference Between `Start` and `End` Block

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#120]
0xBhumii

medium

# Ensure a Minimum Difference Between `Start` and `End` Block

## Summary
To avoid the possibility of starting and ending the farming process in consecutive blocks, there should be a minimum difference enforced between the `startBlock` and `endBlock` parameters, even though these parameters are set by the owner.

## Vulnerability Detail
If the owner sets the `startBlock` and `endBlock` to the same block or consecutive blocks, it could lead to ineffective farming periods where users do not have sufficient time to participate and earn rewards. This could undermine the trust in the system and result in a poor user experience.

## Impact
Starting and ending farming in the same or consecutive blocks could make the farming process ineffective, causing users to miss out on rewards and diminishing the utility of the farming contract.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L272C1-L304C1
## Tool used

Manual Review

## Recommendation
Enforce a minimum block difference between `startBlock` and `endBlock` to ensure a meaningful farming period.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the limit check is a low finding especially when this is an admin call
