### ISSUE TITLE
0xBhumii - Potential Overflow in `_getBlockMultiplier` Function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#121]
0xBhumii

medium

# Potential Overflow in `_getBlockMultiplier` Function

## Summary
The `_getBlockMultiplier` function can potentially overflow, which could lead to incorrect calculations and distribution of rewards
## Vulnerability Detail

Without proper checks, the multiplication operation in `_getBlockMultiplier` can overflow, especially when dealing with large numbers of blocks.

## Impact
An overflow in the block multiplier calculation can lead to incorrect reward calculations, which may result in either excessive or insufficient distribution of rewards, undermining the integrity of the contract.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L339C4-L349C6
## Tool used

Manual Review

## Recommendation
Use the SafeMath library for subtraction and addition to prevent overflow.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because SafeMath is available in Solidity 8
