### ISSUE TITLE
zzykxx - `_withUpdate` flag in `set()`/`add()` should not be optional if `startBlock` has already been reached

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#122]
zzykxx

medium

# `_withUpdate` flag in `set()`/`add()` should not be optional if `startBlock` has already been reached

## Vulnerability Detail
The functions [add()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L153) and [set()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L195) both:
- Change the `totalAllocPoint` global parameter
- Change the `allocPoint` parameter of the specified pool 
- Allow a flag `_withUpdate` to decide if every existing pool `accPointsPerShare` should be updated

Both `totalAllocPoint` and `allocPoint` are parameters that have an impact on how points many points a pool can accumulate, as can be seen in the [updatePool()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L424C1-L428C29) function. 

## Impact
If  [add()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L153) or [set()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L195) are called and `_withUpdate` is passed as `false` when the protocol `startBlock` has been reached (ie. the pools are already accumulating points) then the points calculations will be skewed. 

When `startBlock` has been reached pools should be updated no matter what, there is no reason to make it optional.

## Tool used

Manual Review

## Recommendation
Force both [add()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L153) and [set()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L195) to update the pools if `startBlock` has been reached:
```solidity
if (_withUpdate || block.number >= startBlock) {
    massUpdatePools();
}
```

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/6d117397d57a39a865cee0621cabf9154fb6fd71

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
