### ISSUE TITLE
0xBhumii - Gas Optimization and DoS Vulnerability in `getOptimizedUserInfo` and `getPendingPoints` Functions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#124]
0xBhumii

medium

# Gas Optimization and DoS Vulnerability in `getOptimizedUserInfo` and `getPendingPoints` Functions

## Summary
The `getOptimizedUserInfo` and `getPendingPoints` functions in the contract use extensive loops to retrieve user and pool information, potentially leading to high gas costs and susceptibility to denial-of-service (DoS) attacks. Gas optimization measures, pagination, and off-chain processing are recommended to mitigate these risks.

## Vulnerability Detail
The vulnerability lies in the `getOptimizedUserInfo` and `getPendingPoints` functions, which iterate over all the users and pools to retrieve their respective information. These functions are marked as view, implying that they should not modify the state of the contract. However, due to their extensive loops, they may consume excessive gas if the number of users is significant.
## Impact
This vulnerability could lead to a denial-of-service (DoS) attack by causing out-of-gas errors. An attacker could repeatedly call these functions with a large number of users or pools, causing legitimate users to be unable to interact with the contract due to high gas costs.
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L898C4-L934C2
## Tool used

Manual Review

## Recommendation
Optimize Loops: Refactor the logic within `getOptimizedUserInfo` and `getPendingPoints` to minimize gas consumption.                                                              Consider offloading some computation to off-chain processes to reduce Ethereum network burden.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the input array size can be caller controlled
