### ISSUE TITLE
samuraii77 - Bridging funds could be DOSed

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#131]
samuraii77

medium

# Bridging funds could be DOSed

## Summary
Bridging funds could be DOSed
## Vulnerability Detail
After the farming and withdrawing periods are over, any user can bridge the deposited funds using `bridgePool()`. Then, the `isBridged` mapping gets set to true for that particular pool. In case of any fail of the bridging, the owner can call this function:
```solidity
    function revertFailedBridge(uint256 _pid) external onlyOwner {
        isBridged[_pid] = false;
    }
```
Then, `bridgePool()` can be called again, this time hopefully successfully. However, there is a possible issue that will occur in case a token like USDT gets added as a pool token.

As confirmed with the sponsors, there will be other pool tokens added to the whitelist.
If USDT gets added to the whitelist, the following issue can occur:
1. `bridgePool()` gets called at the appropriate time
2. The function passes but the bridging is not successful so the owner calls `revertFailedBridge()`
3. The function gets called again but this time it will revert and will be DOSed forever due to the following line:
```solidity
lpToken.approve(address(bridge), depositAmount);
```
Since USDT was already approved during the first call of the function, the next time it gets called it will revert as USDT does not allow non-zero to non-zero approvals. This will cause the function to be DOSed permanently and cause the funds to be locked.
## Impact
Bridging funds could be DOSed
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L748-L778
## Tool used

Manual Review

## Recommendation
Use `safeERC20`

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because bridge logic not implemented and not covered by this audit

**Comment by samuraii77** [comment]
Escalate

My issue relies just on code available and in scope for this audit. The developer's intent is clear - they have intentionally created a function `revertFailedBridge()` for situations where `bridgePool()` was not successful according to their standards. If that happens and the token used was USDT which as stated by the developers, will be added, then the issue mentioned above will occur.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> My issue relies just on code available and in scope for this audit. The developer's intent is clear - they have intentionally created a function `revertFailedBridge()` for situations where `bridgePool()` was not successful according to their standards. If that happens and the token used was USDT which as stated by the developers, will be added, then the issue mentioned above will occur.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
Please see sponsor's comment on #147 that's similarly reported to your report:

"bridge is not implemented yet. this is just a marketing stub. we will have separate audit for the bridge when we develop it"

**Comment by WangSecurity** [comment]
Based on the contests README:

> Any bridging related code is considered out of scope

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [samuraii77](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/131/#issuecomment-2143732691): rejected
