### ISSUE TITLE
ni8mare - Updating the lastRewardBlock after the first deposit leads to loss in rewards accumulation for the users.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#132]
ni8mare

high

# Updating the lastRewardBlock after the first deposit leads to loss in rewards accumulation for the users.

## Summary
Updating the lastRewardBlock after the first deposit leads to loss in rewards accumulation for the users.

## Vulnerability Detail

<img width="724" alt="Screenshot 2024-05-24 at 2 08 45 PM" src="https://github.com/sherlock-audit/2024-05-sophon-NishithPat/assets/51897810/e6eb1881-8462-47e6-aecb-02b7dacc4bd8">

The image above easily sums up the issue.

Let's say that the owner has set the `startBlock` as block - 0 and `endBlock` as block - 100.

At block 10, the first `deposit` happens.

If you look at the flow of calls, `deposit` calls `_deposit` which then calls the `updatePool` function. The following if block in `updatePool` gets executed -

```solidity
        uint256 lpSupply = pool.amount;
        uint256 _pointsPerBlock = pointsPerBlock;
        uint256 _allocPoint = pool.allocPoint;
        if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0) {
            pool.lastRewardBlock = getBlockNumber();
            return;
        }
```
Note that `lpSupply` or `pool.amount` is 0 because no deposits before this deposit were called. `pool.amount` only gets updated in functions like deposit and withdraw which did not happen before this deposit function was called. Hence, the if block gets executed and `pool.lastRewardBlock = getBlockNumber();`. This updation of `pool.lastRewardBlock` here is problematic as it leads to a loss of reward accumulation. The value returned by `_getBlockMultiplier` decreases.

Due to this update, the lastRewardBlock is set to 10. But, rewards started accumulating from block - 0. So, the rewards that would have accumulated from blocks 0 - 10 have been lost.

Let's say that another deposit happens at block - 15. So, the value returned by `_getBlockMultiplier(pool.lastRewardBlock, getBlockNumber())` at block - 15 inside `updatePool` will be:

`(_to - _from) * 1e18` = (15 - 10) * 1e18 = 5e18

`from` equals 10 because the first deposit updated the `lastRewardBlock` to 10. Had the first deposit transaction not updated the value of `lastRewardBlock` it would still have been equal to 0. In that case, the value returned by `_getBlockMultiplier(pool.lastRewardBlock, getBlockNumber())` would be:

`(_to - _from) * 1e18` = (15 - 0) * 1e18 = 15e18

There is clearly a loss in reward accumulation.

As `blockMultiplier` (`_getBlockMultiplier(pool.lastRewardBlock, getBlockNumber())`) is used to calculate the value of `pointReward` and `pool.accPointsPerShare`, these values will decrease because of incorrect updation.

Note, that the severity of the issue depends on when the first deposit happens. The situation above could have been even more worse if the first deposit was made on block - 50 or block - 80.

## Impact
Rewards accumulate from block - 0. So, when latestRewardBlock is updated to be equal to block - 10 on the first deposit. There is a clear loss of rewards because rewards from from block - 0 to block - 10 are not taken into to account.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L419-L421

## Tool used

Manual Review

## Recommendation

The if block within the `updatePool` function needs to be updated as:

```solidity
        if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0) {
            return;
        }
```

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it's fairly designed to be time based. Many users would have deposited before farming started standing by for full optimization

**Comment by NishithPat** [comment]
Escalate

@mystery0x 

Your comment -
"Many users would have deposited before farming started standing by for full optimization"

You are assuming that users would deposit before farming starts. This assumption is not right.

You cannot guarantee that the users will deposit before farming starts.  Even this issue - https://github.com/sherlock-audit/2024-05-sophon-judging/issues/195 considers that a pool can be inactive without deposits. If this issue can be deemed valid for assuming inactive pools (with no deposits prior to farming, deposits being made only after farming starts), then why can't the issue I linked above be valid? It is also claiming inactive pools. 

Even if issue 195 is later deemed invalid, inactive pools are indeed possible. And when that happens, deposits that are made after farming starts will lose out on rewards as `pool.lastRewardBlock = getBlockNumber();`. There is a clear loss in value to the users as the time between `startBlock` (which was set in the initialiser) and the first deposit is not considered for rewards/

The thinking behind this issue (https://github.com/sherlock-audit/2024-05-sophon-judging/issues/132) is a little similar to this one - https://0xmacro.com/blog/synthetix-staking-rewards-issue-inefficient-reward-distribution/ 

Please have a look at the issue in the blog before invalidating this issue. 

Also, look at this issue - https://github.com/code-423n4/2023-06-lybra-findings/issues/484

These types of issues have been judged as valid.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> @mystery0x 
> 
> Your comment -
> "Many users would have deposited before farming started standing by for full optimization"
> 
> You are assuming that users would deposit before farming starts. This assumption is not right.
> 
> You cannot guarantee that the users will deposit before farming starts.  Even this issue - https://github.com/sherlock-audit/2024-05-sophon-judging/issues/195 considers that a pool can be inactive without deposits. If this issue can be deemed valid for assuming inactive pools (with no deposits prior to farming, deposits being made only after farming starts), then why can't the issue I linked above be valid? It is also claiming inactive pools. 
> 
> Even if issue 195 is later deemed invalid, inactive pools are indeed possible. And when that happens, deposits that are made after farming starts will lose out on rewards as `pool.lastRewardBlock = getBlockNumber();`. There is a clear loss in value to the users as the time between `startBlock` (which was set in the initialiser) and the first deposit is not considered for rewards/
> 
> The thinking behind this issue (https://github.com/sherlock-audit/2024-05-sophon-judging/issues/132) is a little similar to this one - https://0xmacro.com/blog/synthetix-staking-rewards-issue-inefficient-reward-distribution/ 
> 
> Please have a look at the issue in the blog before invalidating this issue. 
> 
> Also, look at this issue - https://github.com/code-423n4/2023-06-lybra-findings/issues/484
> 
> These types of issues have been judged as valid.

You've deleted an escalation for this issue.

**Comment by mystery0x** [comment]
https://github.com/code-423n4/2023-06-lybra-findings/issues/484 is a different scenario because the reward has been sent into the contract supposedly attributable to the first batch of depositors.

Sophon point farming is purely time based though. If the first depositor comes in late, the first update of pool.accPointsPerShare will be fairly based on the late start then.

**Comment by NishithPat** [comment]
Can you elaborate on why this issue is different from the one in the lybra finding? @mystery0x 
I think they are quite similar.

Yes, Sophon point farming is time-based. Hence, not including the time period between the start of farming and the first deposit is incorrect as it directly results in a loss of rewards. Don't you think this statement is right?

**Comment by NishithPat** [comment]
It looks like the issue will be rejected anyway. But, I am still not quite convinced with the judging for this one.
