### ISSUE TITLE
Tricko - weETH and wstETH pools share the same `allocPoint`.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#134]
Tricko

medium

# weETH and wstETH pools share the same `allocPoint`.

## Summary
The weETH and wstETH pools use the same `allocPoint`, but their exchange rates are not 1:1. Consequently, depositing the same USD value into one pool results in fewer reward points than depositing into the other, which is unfair to users.

## Vulnerability Detail
Each pool computes rewards proportionally to its `allocPoint`, but both weETH and wstETH pools share the same `allocPoint` (see code below). However, these two tokens have different prices.

```solidity
//Snippet from updatePool()
uint256 pointReward =
    blockMultiplier *
    _pointsPerBlock *
    _allocPoint /
    totalAllocPoint;


pool.accPointsPerShare = pointReward /
    lpSupply +
    pool.accPointsPerShare;
}
```

Based on the prices at the time of writing this report, weETH is worth $3,843, while wstETH is worth $4,306. As a result, for the same USD value, you can deposit more weETH tokens than wstETH tokens. Therefore, depositing into the wstETH pool yields fewer points per dollar for the user.

## Impact
Depending on the relative prices of weETH and wstETH, depositing in one pool will result in fewer reward points than intended.

## Code Snippet
pools creation
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L131-L140

points calculation
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L424-L432

## Tool used
Manual Review.

## Recommendation
Consider using different `allocPoint` for the weETH and wstETH pools, based on their relative prices.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because set() can always be used to updates a given pool's allocation point if need be
