### ISSUE TITLE
hunter_w3b - Zero `lpSupply` Causes Incorrect Calculations of `rewardSettled` and `rewardDebt`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#137]
hunter_w3b

high

# Zero `lpSupply` Causes Incorrect Calculations of `rewardSettled` and `rewardDebt`

## Summary

When the `updatePool` function is called during the first deposit, the `lpSupply` is zero, causing the function to return without updating `pool.accPointsPerShare`. This results in the `rewardSettled` and `rewardDebt` being set to zero for the first depositor and potentially for other depositors if multiple transactions occur in the same block.

## Vulnerability Detail

Whenever the protocol initializes sDai, wstETH, and weETH pools, the values that are initialized are:

```solidity
        poolInfo.push(
            PoolInfo({
                lpToken: IERC20(_lpToken),
                l2Farm: address(0),
                amount: 0,
                boostAmount: 0,
                depositAmount: 0,
                allocPoint: _allocPoint,
                lastRewardBlock: lastRewardBlock,
@>>                accPointsPerShare: 0,
                description: _description
            })
        );
```

for each pool.

However, when the first depositor deposits into any of these pools, `rewardSettled` and `rewardDebt` are set to zero because `pool.accPointsPerShare` is zero, resulting in the calculation of `rewardSettled` and `rewardDebt` being zero.

```solidity
    function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_depositAmount == 0) {
            revert InvalidDeposit();
        }
        if (_boostAmount > _depositAmount) {
            revert BoostTooHigh(_depositAmount);
        }

        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
@>>        updatePool(_pid);

        uint256 userAmount = user.amount;
        user.rewardSettled =
            userAmount *
@>>            pool.accPointsPerShare / // @audit pool.accPointsPerShare is zero   so the calc is zero
            1e18 +
            user.rewardSettled -
            user.rewardDebt;

        // booster purchase proceeds
        heldProceeds[_pid] = heldProceeds[_pid] + _boostAmount;

        // deposit amount is reduced by amount of the deposit to boost
        _depositAmount = _depositAmount - _boostAmount;

        // set deposit amount
        user.depositAmount = user.depositAmount + _depositAmount;
        pool.depositAmount = pool.depositAmount + _depositAmount;

        // apply the boost multiplier
        _boostAmount = _boostAmount * boosterMultiplier / 1e18;

        user.boostAmount = user.boostAmount + _boostAmount;
        pool.boostAmount = pool.boostAmount + _boostAmount;

        // userAmount is increased by remaining deposit amount + full boosted amount
        userAmount = userAmount + _depositAmount + _boostAmount;

        user.amount = userAmount;
@>>        pool.amount = pool.amount + _depositAmount + _boostAmount;

        user.rewardDebt = userAmount *
@>>            pool.accPointsPerShare /
            1e18;

        emit Deposit(msg.sender, _pid, _depositAmount, _boostAmount);
    }
```

In the `_deposit` function, before we update the state, we call the `updatePool(_pid)` function for a pool.

```solidity
    function updatePool(uint256 _pid) public {
        PoolInfo storage pool = poolInfo[_pid];
        if (getBlockNumber() <= pool.lastRewardBlock) {
            return;
        }
@>>        uint256 lpSupply = pool.amount;   // @audit the pool.amount is zero for the first depositor
        uint256 _pointsPerBlock = pointsPerBlock;
        uint256 _allocPoint = pool.allocPoint;
@>>        if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0) {
            pool.lastRewardBlock = getBlockNumber();
            return;
        }
        uint256 blockMultiplier = _getBlockMultiplier(pool.lastRewardBlock, getBlockNumber());
        uint256 pointReward =
            blockMultiplier *
            _pointsPerBlock *
            _allocPoint /
            totalAllocPoint;

@>>        pool.accPointsPerShare = pointReward /
            lpSupply +
            pool.accPointsPerShare;

        pool.lastRewardBlock = getBlockNumber();
    }
```

In this function, if the `lpSupply` is zero because no amount has been added to the pool yet, the function will return without updating the `pool.accPointsPerShare` variable. In that case, `rewardSettled` and `rewardDebt` will be zero.

```solidity
        user.rewardSettled =
            userAmount *
            pool.accPointsPerShare / // @audit pool.accPointsPerShare is zero   so the calc is zero
            1e18 +
            user.rewardSettled -
            user.rewardDebt;

        user.rewardDebt = userAmount *
            pool.accPointsPerShare /
            1e18;
```

In the worst case, `pool.lastRewardBlock` is assigned to `getBlockNumber()`. If in the same block another transaction occurs, its `rewardSettled` and `rewardDebt` will also be set to zero, and the value of pool.lastRewardBlock will again be updated.

```solidity
        if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0) {
            pool.lastRewardBlock = getBlockNumber();
            return;
        }
```

## Impact

It prevents the proper accumulation and distribution of points for the first depositor in a newly initialized pool. Since `pool.accPointsPerShare` is not updated, the reward calculation formulas yield zero, resulting in inaccurate reward allocations. This can lead to discrepancies in the reward distribution across different depositors.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L573-L625

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L410-L436

## Tool used

Manual Review

## Recommendation

There are two ways to correct this issue:

1. Add an Initial Amount to the Pool: Ensure that the pool has a non-zero amount from the start so that the `updatePool` function does not return early.

2. Initialize `accPointsPerShare` with a Non-Zero Value: Add an initial value to `accPointsPerShare` to ensure it is updated even if the pool's amount is zero at the start.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because that's the intended design for the first depositor
