### ISSUE TITLE
nikhil840096 - Restricted Balance Handling in `SophonFarming.sol:withdrawProceeds` Function.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#140]
nikhil840096

high

# Restricted Balance Handling in `SophonFarming.sol:withdrawProceeds` Function.

## Summary
The `withdrawProceeds` function in the contract allows the owner to withdraw proceeds stored in the `heldProceeds` mapping.
If `heldProceeds[_pid]` holds a value just one `wei` less than the actual balance, the withdrawal will fail.

## Vulnerability Detail
* The withdrawal amount entirely relies on the value stored in `heldProceeds[_pid]`. This variable determines how much the owner can withdraw. The issue arises because the withdrawal amount is entirely dependent on the value stored in `heldProceeds[_pid]`. If the actual balance of the contract is less than the amount stored in `heldProceeds[_pid]` (even by a single wei), the transaction will revert. This is due to the safeTransfer function, which fails if the contract’s balance is insufficient. 

## Impact
Significant funds may be locked in the contract, becoming inaccessible to the owner. This situation can cause operational issues and financial losses, as the owner may be unable to withdraw proceeds.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L863-L869

## Tool used

Manual Review

## Recommendation
Add a check which   checks the balance of the contract and accordingly withdraw from it or add input amount to withdraw.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because there's no rounding entailed when assigning heldProceeds[_pid] to _proceeds
