### ISSUE TITLE
zzykxx - USDT can't be bridged out

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#147]
zzykxx

medium

# USDT can't be bridged out

## Summary
The protocol is not compatible with some tokens that don't return a boolean on approval, like USDT.

## Vulnerability Detail
The function [bridgePool()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L748) approves the token of the specified pool via `approve()`:
```solidity
...SNIP...
IERC20 lpToken = pool.lpToken;
lpToken.approve(address(bridge), depositAmount);
...SNIP...
```

This will revert if `lpToken` doesn't return a boolean because the interface expects a boolean to be returned. 

Tokens that return `false` on approvals failure are also not managed correctly because the return value is ignored, but this would lead to the transaction failing anyway when the token transfer is attempted so it's not an issue. 

## Impact
This will prevent the admins from bridging the staked tokens after the withdrawal period is ended, leading to the tokens being stuck in the contract.

## Tool used

Manual Review

## Recommendation
Use `safeApprove()` instead of `approve()`.

**Comment by RomanHiden** [comment]
bridge is not implemented yet. this is just a marketing stub. we will have separate audit for the bridge when we develop it

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because bridge logic not implemented and not covered by this audit

**Comment by Audinarey** [comment]
Sponsor's comment does not hold water in this case considering sherlock rules

> If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.

Market stub or not, The rule applies here

**Comment by Audinarey** [comment]
Escalate

Sponsor's comment does not hold water in this case considering sherlock rules

> If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.

Market stub or not, The rule applies here
