### ISSUE TITLE
EgisSecurity - `massUpdatePools` should always be called when calling `add` and `set`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#150]
EgisSecurity

medium

# `massUpdatePools` should always be called when calling `add` and `set`

## Summary
`set` and `add` both have an argument `_withUpdate`

If it's true, then `massUpdatePools` will be called.

```solidity
 function set(uint256 _pid, uint256 _allocPoint, bool _withUpdate) public onlyOwner {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_withUpdate) {
            massUpdatePools();
        }
...
```

```solidity
 function add(uint256 _allocPoint, address _lpToken, string memory _description, bool _withUpdate) public onlyOwner returns (uint256) {
        if (poolExists[_lpToken]) {
            revert PoolExists();
        }
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_withUpdate) {
            massUpdatePools();
        }
...
```

The problem is if `_withUpdate` is false. Since both functions change `totalAllocPoint` and `set` also modifies a pool's `allocPoint`, if `massUpdatePool` isn't called, then the changes to the above variables, will have an effect from each pool's `lastRewardBlock`, basically it will be like that's when the change happened.
## Vulnerability Detail
Example:
1. There is a pool with `lastRewardBlock = 10`.
2. Currently we are at the block 20, if `set` with `_withUpdate = false` is called and the `allocPoint` of the pool is changed, the the change will affect the blocks from `lastRewardBlock` up to `block.number`. which is incorrect. as these blocks have already passed and we are basically making changes in the past this way.

There is another issue that crops up, if the protocol designed `set` and `add` so that the above mentioned "issue" is a feature (affecting point calculation of blocks in the past), the it can be very easily griefed by anyone, as `massUpdatePool` has no access modifier

Example:
1. There is a pool with `lastRewardBlock = 10`.
2. Currently we are at the block 20, if `set` with `_withUpdate = false` is called and the `allocPoint` of the pool is changed, the the change will affect the blocks from `lastRewardBlock` up to `block.number`. In this case this is wanted by the protocol.
3. Before `set` is called, a user simply front runs the tx and calls `massUpdatePools`. This way all the pool's `lastRewardBlock = block.number`, so the affect that the protocol desired (affecting the points for old blocks) is nullified and griefed.

The exact same issues will happen in `add` as well.
## Impact
Inconsistent point calculation (if the issue is points being awarded differently than expected)
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L153
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L195
## Tool used

Manual Review

## Recommendation
The best way to fix both problems is to remove `_withUpdate` and always call `massUpdatePools`. This way both potential issues will be fixed

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/6d117397d57a39a865cee0621cabf9154fb6fd71

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
