### ISSUE TITLE
sajjad - The owner can immediately end the farming and withdrawal phase intentionally or by mistake.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#151]
sajjad

medium

# The owner can immediately end the farming and withdrawal phase intentionally or by mistake.

## Summary
The [`setEndBlock`](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L287) function at line `287` of `SophonFarming.sol` allows the owner to set `endBlock` and `endBlockForWithdrawals`. If the owner sets `_endBlock` to the current block number and `_withdrawalBlocks` to `0`, assets will be locked permanently without giving users the opportunity to withdraw them.

## Tool Used
Manual Review

## Recommendation
There should be a check in the `setEndBlock` function to ensure that `_withdrawalBlocks` is not less than a value such as 50400 (1 week), so users have the opportunity to withdraw their assets.
```diff
function setEndBlock(uint256 _endBlock, uint256 _withdrawalBlocks) public onlyOwner {
        uint256 _endBlockForWithdrawals;
        if (_endBlock != 0) {
            if (_endBlock <= startBlock || getBlockNumber() > _endBlock) {
                revert InvalidEndBlock();
            }
+           if (_withdrawalBlocks >= 50400) {
+                revert withdrawalBlocksLessThanLimit();
+           }
            if (isFarmingEnded()) {
                revert FarmingIsEnded();
            }
            _endBlockForWithdrawals = _endBlock + _withdrawalBlocks;
        } else {
            // withdrawal blocks needs an endBlock
            _endBlockForWithdrawals = 0;
        }
        massUpdatePools();
        endBlock = _endBlock;
        endBlockForWithdrawals = _endBlockForWithdrawals;
    }
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because admin is trusted and will not do this insensibly
