### ISSUE TITLE
adamidarrha - Failure to Convert ETH/WETH to DAI in SophonFarming Protocol Leads to breaking of functionality and Potential Loss of Funds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#154]
adamidarrha

medium

# Failure to Convert ETH/WETH to DAI in SophonFarming Protocol Leads to breaking of functionality and Potential Loss of Funds

## Summary

the `SophonFarming` contract facilitates staking of LP tokens in various pools to earn rewards. It supports deposits in ETH/WETH, which are intended to be converted into specific assets like stETH or eETH based on the user's choice before being wrapped. However, the protocol neglects to convert ETH to DAI when users attempt to deposit into the sDAI pool, leading to transaction failures or potential loss of funds.

## Vulnerability Detail

the function `depositEth` and `depositWeth` in `SophonFarming` contract are designed to allow users to deposit ETH or WETH: :

```solidity=503
function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
        if (msg.value == 0) {
            revert NoEthSent();
        }

        uint256 _finalAmount = msg.value;
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
        }
        
        _depositPredefinedAsset(_finalAmount, msg.value, _boostAmount, _predefinedPool);
    }
```

This function properly swaps ETH to eETH or stETH depending on the user's chosen pool. However, it fails to perform a necessary conversion from ETH to DAI when targeting the sDAI pool, incorrectly using the raw ETH amount for further operations.

```solidity=548
function _depositPredefinedAsset(uint256 _amount, uint256 _initalAmount, uint256 _boostAmount, PredefinedPool _predefinedPool) internal {

        uint256 _finalAmount;

        if (_predefinedPool == PredefinedPool.sDAI) {
            _finalAmount = _daiTOsDai(_amount);
        } else if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _stEthTOwstEth(_amount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _eethTOweEth(_amount);
        } else {
            revert InvalidDeposit();
        }

        // adjust boostAmount for the new asset
        _boostAmount = _boostAmount * _finalAmount / _initalAmount;

        _deposit(typeToId[_predefinedPool], _finalAmount, _boostAmount);
    }
```

In scenarios where the user selects the sDAI pool, the ETH amount is mistakenly treated as DAI. This error can lead to two major issues:

1. Transaction reverts: If the contract lacks sufficient DAI, the call to _daiTOsDai will fail, causing the user's transaction to revert.
2. Loss of funds: If the contract possesses enough DAI, the deposited ETH is inaccurately accounted as an equivalent amount of DAI, severely devaluing the user's deposit. This misaccounting prevents users from retrieving their deposited ETH in its full value.

## Impact

breaking of functionality of depositing eth/weth to sdai pool, or loss of funds.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L503-L516

https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L524-L539
## Tool used

Manual Review

## Recommendation

in `depositEth` and `depositWeth` , swap eth to dai:
```diff=503
function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
        if (msg.value == 0) {
            revert NoEthSent();
        }

        uint256 _finalAmount = msg.value;
+        if (_predefinedPool == PredefinedPool.sDAI) {
+            _finalAmount = _ethTODAI(_finalAmount);
```

where _ethToDAI is a function that swaps ETH to DAI in a dex.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because user input validation to prevent user mistakes is not considered a valid issue. Additionally, the likelihood of the scenario happening is extremely low

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/f0b82fd83a5d85eb8dc7ba2bbce2d49fefb326a4

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
