### ISSUE TITLE
utsav - `setStartBlock` doesn't update the `lastRewardBlock`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#155]
utsav

medium

# `setStartBlock` doesn't update the `lastRewardBlock`

## Summary
`setStartBlock` doesn't update the `lastRewardBlock`  and this can lead to `wrong` reward calculation

## Vulnerability Detail
Owner can update the startBlock before farming started
```solidity
    function setStartBlock(uint256 _startBlock) public onlyOwner {
        if (_startBlock == 0 || (endBlock != 0 && _startBlock >= endBlock)) {
            revert InvalidStartBlock();
        }
        if (getBlockNumber() > startBlock) {
            revert FarmingIsStarted();
        }
        startBlock = _startBlock;
    }
```
But the issue is `setStartBlock` doesn't `update` lastRewardBlock of pools. As a result `pool` will be started earlier or later but `reward` will be calculated based on old `lastRewardBlock`

## Impact
User can get less/more reward than expected

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L272C1-L280C6

## Tool used
Manual Review + VS code

## Recommendation
`Update` the `lastRewardBlock` while updating `startBlock`

Duplicate of #108

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  valid because lastRewardBlock for each pool should indeed sync with the latest startBlock

**Comment by mystery0x** [comment]
This report should be valid as it described both scenarios 1 and 2 (albeit in a simpler way) of https://github.com/sherlock-audit/2024-05-sophon-judging/issues/108.
