### ISSUE TITLE
EgisSecurity - SophonFarming.sol - `startBlock` can change and be in the past

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#156]
EgisSecurity

high

# SophonFarming.sol - `startBlock` can change and be in the past

## Summary
`startBlock` is used when creating a new pool, using `add`, it's used to specify the start block of when the pool will start accruing points.
```solidity
uint256 lastRewardBlock =
            getBlockNumber() > startBlock ? getBlockNumber() : startBlock;
```
As you can see it always has to be in the future, otherwise `block.number` is used as `lastRewardBlock`.
The contract also allows the changing of the `startBlock` by using `setStartBlock`.
```solidity
function setStartBlock(uint256 _startBlock) public onlyOwner {
        if (_startBlock == 0 || (endBlock != 0 && _startBlock >= endBlock)) {
            revert InvalidStartBlock();
        }
        if (getBlockNumber() > startBlock) {
            revert FarmingIsStarted();
        }
        startBlock = _startBlock;
    }
```
Again the function enforces that `startBlock` is in the future and not less than `block.number`.
Now, the contract can also change the `lastRewardBlock` of a pool, in set.

```solidity
function set(uint256 _pid, uint256 _allocPoint, bool _withUpdate) public onlyOwner {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_withUpdate) {
            massUpdatePools();
        }

        PoolInfo storage pool = poolInfo[_pid];
        address lpToken = address(pool.lpToken);
        if (lpToken == address(0) || !poolExists[lpToken]) {
            revert PoolDoesNotExist();
        }
        totalAllocPoint = totalAllocPoint - pool.allocPoint + _allocPoint;
        pool.allocPoint = _allocPoint;

        if (getBlockNumber() < pool.lastRewardBlock) {
            pool.lastRewardBlock = startBlock;
        }

        emit Set(lpToken, _pid, _allocPoint);
    }
```
The function is used for changing the `allocPoint` of a pool and the `totalAllocPoint` respectively, but it also will change the `lastRewardBlock` of a pool, if `block.number < pool.lastRewardBlock`.

This is only possible when a pool is created and `startBlock` is used for `lastRewardBlock`. 
As `startBlock` is always a future block.

Knowing this and knowing that `startBlock` always has to be in the future, there can be a nasty side effect of calling `set`.
## Vulnerability Detail
Imagine the following scenario:
1. We are at block 10 and `startBlock = 50`, so any new pools created will have a `lastRewardBlock = 50` and will start accruing points at block 50.
2. Alice deposits in one of the new pools (pid = 1) and she will start accruing points after block 50.
3. We are now at block 20 and the protocol decides to create another pool, but wants its `lastRewardBlock = 30`, so they first call `setStartBlock` and set `startBlock = 30`.
4. Then they use `add` to create the new pool (pid = 2), with `lastRewardBlock = 30`, so it will start accruing points after block 30.
5. We are now at block 40, the newly added pool is active and everything works fine, but the protocol decides to use set to change the `allocPoint` of the the first pool (pid = 1), remember that it's `lastRewardBlock = 50`.
6. The alloc point is changed and then this line is hit:
```solidity
if (getBlockNumber() < pool.lastRewardBlock) {
            pool.lastRewardBlock = startBlock;
        }
```
This will return `true`, as `40 < 50`, so the `lastRewardBlock = 30`, as `startBlock = 30`, this means that the `lastRewardBlock` was set in the past.
7. The problem is that users that deposited before the 40-th block are now eligible for points, even users that deposited after the 30-th block, because when they first deposited, `lastRewardBlock` was still 50, so `updatePool` just returned, but if now `updatePool` is called, `lastRewardBlock = 30`, so it will accumulate points from the 30-th to the 40-th block, but there can be deposits between those blocks, and users that deposited between those blocks, will still get points, which shouldn't be the case.

## Impact
Inconsistent point calculation (if the issue is points being awarded differently than expected)

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L211-L213
## Tool used

Manual Review

## Recommendation
Only change the `lastRewardBlock` if the new `startBlock` is in the future

Duplicate of #108

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  valid because lastRewardBlock for each pool should indeed sync with the latest startBlock

**Comment by mystery0x** [comment]
This report should be valid as it described scenario 1 of https://github.com/sherlock-audit/2024-05-sophon-judging/issues/108.
