### ISSUE TITLE
0xkmg - When using `add()` and `set()`, it should always call `massUpdatePools()` to update all pools

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#157]
0xkmg

medium

# When using `add()` and `set()`, it should always call `massUpdatePools()` to update all pools

## Summary

The `totalAllocPoint` variable is crucial in determining the share of the total reward each pool receives, making it a key component in reward calculations. If the totalAllocPoint is altered without first updating the pending rewards, the reward distribution for each pool will be miscalculated. 

For instance, when _withUpdate is set to `false` in the `add()` function, as shown below, the totalAllocPoint is changed without updating the rewards through massUpdatePools().

## Vulnerability Detail

Assuming that on block 1000000, pointsPerBlock is 5 per block, totalAllocPoint is 5000, and
allocPoint of pool id 0 is 500.

block 1000000 - All pools’ points are updated
block 1100000  - A new pool is added 
block 1100000 - totalAllocPoint to be changed from 5000 to 10000
block 1200000 - The pools’ rewards are updated once again.

From current logic, the total points allocated to the pool id 0 during block 1000000 to 1200000 is equal to 

pointsPerBlock*pool0allocPoint/totalAllocPoint = 50,000 

However, the points should be calculated by accounting for the original totalAllocPoint value during the period when it is not yet updated as follows:

block 1000000 - pointsPerBlock*pool0allocPoint/totalAllocPoint = 50,000 
block 1100000 - pointsPerBlock*pool0allocPoint/totalAllocPoint = 25,000 

The correct total points is 75,000, which is different from the miscalculated reward by 25,000.

## Impact

Points are miscalculated. 

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L153-L187

## Tool used

Manual Review

## Recommendation

Removing the _withUpdate variable in the add() and set() functions and always calling the massUpdatePools() function before updating totalAllocPoint variable.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/6d117397d57a39a865cee0621cabf9154fb6fd71

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
