### ISSUE TITLE
no - The formula for calculating reward points is incorrect in deposit , withdraw and increaseBoost

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#158]
no

high

# The formula for calculating reward points is incorrect in deposit , withdraw and increaseBoost

## Summary
The formula for calculating reward points is incorrect in deposit , withdraw and increaseBoost
## Vulnerability Detail
The comment specification is in SophonFarmingState.sol is below:
```javascript
//   pending reward = (user.amount * pool.accPointsPerShare) - user.rewardDebt
```
Howerve in  deposit , withdraw and increaseBoost functions,The formula for calculating reward points is like this.
```javascript
function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_depositAmount == 0) {
            revert InvalidDeposit();
        }
        if (_boostAmount > _depositAmount) {
            revert BoostTooHigh(_depositAmount);
        }

        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
        updatePool(_pid);

        uint256 userAmount = user.amount;
        user.rewardSettled =          
            userAmount *
            pool.accPointsPerShare /
    @>        1e18 +
            user.rewardSettled -
            user.rewardDebt;

        // booster purchase proceeds
        heldProceeds[_pid] = heldProceeds[_pid] + _boostAmount;

        // deposit amount is reduced by amount of the deposit to boost
        _depositAmount = _depositAmount - _boostAmount;

        // set deposit amount
        user.depositAmount = user.depositAmount + _depositAmount;
        pool.depositAmount = pool.depositAmount + _depositAmount;

        // apply the boost multiplier
        _boostAmount = _boostAmount * boosterMultiplier / 1e18;

        user.boostAmount = user.boostAmount + _boostAmount;
        pool.boostAmount = pool.boostAmount + _boostAmount;

        // userAmount is increased by remaining deposit amount + full boosted amount
        userAmount = userAmount + _depositAmount + _boostAmount;

        user.amount = userAmount;
        pool.amount = pool.amount + _depositAmount + _boostAmount;

        user.rewardDebt = userAmount *    
            pool.accPointsPerShare /
    @>        1e18;

        emit Deposit(msg.sender, _pid, _depositAmount, _boostAmount);
    }

```
In the above calculation formula, there is an extra division by 1e18.
## Impact
This will result in a reduction of the reward points users can receive.
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L574
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L699
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L631
## Tool used

Manual Review

## Recommendation
Remove the extra division by 1e18

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because removing the division of 1e18 is going to make the assigned values 1e18 bigger
