### ISSUE TITLE
Squilliam - [M-2] `Proxy::fallback` Lack of Withdrawal Mechanism will leaked to permanently locked funds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#16]
Squilliam

medium

# [M-2] `Proxy::fallback` Lack of Withdrawal Mechanism will leaked to permanently locked funds

## Summary
The `Proxy` contract has a vulnerability that allows ether to be permanently locked in the contract. The contract has a `payable` fallback function (`fallback()`) in `Proxy.sol`, which allows it to receive ether. However, the contract does not have any function to withdraw the ether, resulting in the ether being locked in the contract indefinitely.

## Vulnerability Detail

Add the following test to `SophonFarming.t.sol`:
```javascript
function testLockedEtherVulnerability() public {
    // Deploy a new Proxy contract
    Proxy proxyContract = new Proxy(address(0));

    // Send some ether to the Proxy contract
    uint256 etherAmount = 100 ether;
    payable(address(proxyContract)).transfer(etherAmount);

    // Check that the Proxy contract's balance is equal to the sent ether
    assertEq(address(proxyContract).balance, etherAmount, "Proxy contract balance should match the sent ether");

    // Check that the ether remains locked in the contract
    assertEq(address(proxyContract).balance, etherAmount, "Ether should remain locked in the Proxy contract");
}
```
In this test, I could not even try to withdraw the funds because there is no withdraw function

## Impact
Any ether sent to the contract will be permanently locked and cannot be retrieved by any means. This function will lead to a permanent loss of funds, as funds are not able to be recovered by anyone, even admins. Furthermore, the locked ether can accumulate over time, potentially tying up a significant amount of value within the contract.

## Code Snippet
`Proxy::fallback` can be found here:
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/proxies/Proxy.sol?plain=1#L12-L21

## Tool used
Foundry
Manual Review

## Recommendation
Implement a proper withdrawal function that allows the contract owner or authorized parties to retrieve the locked ether.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because Proxy.sol is out of scope
