### ISSUE TITLE
ygoel72 - [Medium] No Storage Gap for Upgradeable Contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#161]
ygoel72

medium

# [Medium] No Storage Gap for Upgradeable Contract

## Summary
Storage of `SophonFarmingState` might be corrupted during an upgrade.

## Vulnerability Detail
For upgradeable contracts, there must be storage gap to "allow developers to freely add new state variables in the future without compromising the storage compatibility with existing deployments" (quote OpenZeppelin). Otherwise it may be very difficult to write new implementation code. Without storage gap, the variable in child contract might be overwritten by the upgraded base contract if new variables are added to the base contract. This could have unintended and very serious consequences to the child contracts, potentially causing loss of user fund or cause the contract to malfunction completely.

Refer to the bottom part of this article: https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable 

- `SophonFarmingState.sol` contract is intended to be upgradeable contract in the code base
However, it does not contain storage gap. The storage gap is essential for upgradeable contract because "It allows us to freely add new state variables in the future without compromising the storage compatibility with existing deployments". Refer to the bottom part of this article:
https://docs.openzeppelin.com/contracts/3.x/upgradeable

If the contract inheriting the base contract contains additional variable, then the base contract cannot be upgraded to include any additional variable, because it would overwrite the variable declared in its child contract. This greatly limits contract upgradeability.

## Impact
Storage of SophonFarmingState might be corrupted during upgrading, thus causing the stateVariables to override unintentionally and break the protocol

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L21 
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarmingState.sol 

## Tool used

Manual Review

## Recommendation
Recommend adding appropriate storage gap at the end of upgradeable contracts such as the below. Please reference OpenZeppelin upgradeable contract templates.
In `SophonFarmingState.sol`
```diff
    mapping(address => bool) public poolExists;

    uint256 public endBlockForWithdrawals;

    BridgeLike public bridge;
    mapping(uint256 => bool) public isBridged;
+  uint256[50] private __gap;
}
```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because simple contracts with one of the parent contract not implementing storage gaps are considered low/informational
