### ISSUE TITLE
samuraii77 - A user can unwillingly lock his tokens at unfavorable terms

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#166]
samuraii77

medium

# A user can unwillingly lock his tokens at unfavorable terms

## Summary
A user can unwillingly lock his tokens at unfavorable terms
## Vulnerability Detail
A user can lock his tokens in order to get points for a potential airdrop. From the amount of tokens he is locking, he can specify an amount of tokens that will be boosted. They will receive a multiplier and thus, get more points but he will not be able to withdraw them. There is a way where this user can unwillingly lock his tokens at unfavorable terms and essentially, just lose them.

Imagine the following scenario:
1. Bob decides to lock his tokens in order to get some points
2. He sees that the current `boosterMultiplier` is 3e18
3. As he likes the multiplier, he decides to deposit 1e18 tokens and boost them all, he expects to get the following boosted amount:
$boostAmount = boostAmount * boosterMultiplier / 1e18$
$boostAmount = 1e18 * 3e18 / 1e18$
$boostAmount = 3e18$
4. Just before he deposits, the owner decides to change the `boosterMultiplier` to 1e18 using `setBoosterMultiplier()`
5. Now, Bob only gets a boost amount of `1e18` tokens which is basically the same he would have got without boosting them
6. He will also not be able to withdraw them as they are boosted

While the owner is trusted, this issue does not rely on the owner trying to game users. He simply decided to change the booster multiplier which made Bob lock all of his funds forever at very unfavorable terms. With enough people using the protocol and locking their tokens, this is almost guaranteed to happen every time the owner decides to change the booster multiplier.

This issue can also arise for every other state variable that has a setter function such as the allocation points for each pool.
## Impact
A user can unwillingly lock his tokens at unfavorable terms
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L322-L331
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L574-L624
## Tool used

Manual Review

## Recommendation
Let the user specify an expected boosted multiplier and revert if it is different.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because an admin action can break certain assumptions about the functioning of the code
