### ISSUE TITLE
Honour - MassPoolUpdate should be a dependent on the farming state rather than being reliant on the Admin

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#167]
Honour

medium

# MassPoolUpdate should be a dependent on the farming state rather than being reliant on the Admin

## Summary

Adding and Setting pools should always update the existing pools if farming is ongoing to prevent stakers from loosing already accumulated points

## Vulnerability Detail

On adding new pools or setting the allocPonits for an existing pool the admin is the one responsible for deciding if the existing pools gets updated or not , the issue is that once farming starts any pool interaction must update existing pools otherwise stakers stand to loose accumulated points as shown below

```sol

//add tests to SophonFarming.t.sol and run with : forge test --match test_setPool_with

function test_setPool_with_update() public {
        uint256 wstPoolId = sophonFarming.typeToId(
            SophonFarmingState.PredefinedPool.wstETH
        );

        uint256 daiPoolId = sophonFarming.typeToId(
            SophonFarmingState.PredefinedPool.sDAI
        );

        vm.startPrank(account1);
        deal(address(wstETH), account1, 100e18);
        wstETH.approve(address(sophonFarming), 100e18);
        sophonFarming.deposit(wstPoolId, 100e18, 0);
        vm.stopPrank();

        vm.roll(block.number + 90);

        uint pointsBefore = sophonFarming.pendingPoints(wstPoolId, account1);

        vm.prank(deployer);
        sophonFarming.set(daiPoolId, 500000, true);

        assertEq(
            pointsBefore,
            sophonFarming.pendingPoints(wstPoolId, account1)
        );
    }

    function test_setPool_without_update() public {
        uint256 wstPoolId = sophonFarming.typeToId(
            SophonFarmingState.PredefinedPool.wstETH
        );

        uint256 daiPoolId = sophonFarming.typeToId(
            SophonFarmingState.PredefinedPool.sDAI
        );

        vm.startPrank(account1);
        deal(address(wstETH), account1, 100e18);
        wstETH.approve(address(sophonFarming), 100e18);
        sophonFarming.deposit(wstPoolId, 100e18, 0);
        vm.stopPrank();

        vm.roll(block.number + 90);

        uint pointsBefore = sophonFarming.pendingPoints(wstPoolId, account1);

        vm.prank(deployer);
        sophonFarming.set(daiPoolId, 50000, false);

        assertTrue(
            pointsBefore > sophonFarming.pendingPoints(wstPoolId, account1)
        );
    }
```

The pool update should be a function of the farming state rather than reliant on the Admin to avoid scenarios where stakers loose points due to human errors/oversight on the admin side

## Impact

Stakers can loose points

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L195-L201

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L153-L162

## Tool used

Manual Review

## Recommendation

add/set should be updated as follows

```sol
function add(uint256 _allocPoint, address _lpToken, string memory _description) public onlyOwner {

  //...code

  if(getBlockNumber() > startBlock) {//if farming has started
    massUpdatePools();
  }

  //...code
}

function set(uint256 _pid, uint256 _allocPoint) public onlyOwner {

  //...code

  if(getBlockNumber() > startBlock) {//if farming has started
    massUpdatePools();
  }
  //...code
}
```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean
