### ISSUE TITLE
Bauer - `gasPerPubdataByte` is incorrect.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#169]
Bauer

medium

# `gasPerPubdataByte` is incorrect.

## Summary
In the `bridgePool()` function, when calling `bridge.deposit()`, the `gasPerPubdataByte` is set to 0, which is incorrect and may cause unexpected issues when the transaction is executed on L2.

## Vulnerability Detail
The `bridgePool()` function is used to bridge assets from the ETH chain to the target chain. Within this function, the protocol calls `bridge.deposit()` to transfer assets to the zkSync chain. However, the parameter `_l2TxGasPerPubdataByte` is set to 0, which is incorrect. 
```solidity
   // These are pending the launch of Sophon testnet
        bridge.deposit(
            pool.l2Farm,            // _l2Receiver
            address(lpToken),       // _l1Token
            depositAmount,          // _amount
            200000,                 // _l2TxGasLimit
            0,                      // _l2TxGasPerPubdataByte
            owner()                 // _refundRecipient
        );

        isBridged[_pid] = true;

```

The `gasPerPubdataByte` parameter is essential for every transaction on zkSync, and the official recommendation is to set it to 800. 
https://docs.zksync.io/build/sdks/js/utils.html#gas
```solidity
export const REQUIRED_L1_TO_L2_GAS_PER_PUBDATA_LIMIT = 800;

```

The best practices also emphasize considering `gasPerPubdataByte`. 
https://docs.zksync.io/build/quick-start/best-practices.html#gasperpubdatabyte-should-be-taken-into-account-in-development
Setting it to 0 in the protocol might lead to unexpected issues with the transaction.

## Impact
Setting it to 0 might lead to unexpected issues with the transaction.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L771

## Tool used

Manual Review

## Recommendation
The recommended fix is to set an appropriate value.

**Comment by sherlock-admin4** [comment]
2 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because bridge logic not implemented and not covered by this audit

**0xreadyplayer1** commented:
>  According to contest Readme `Any bridging related code is considered out of scope` and the issue is invalid.
