### ISSUE TITLE
zarkk01 - Unfair distribution of points due to price volatility of the `lpToken`.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#170]
zarkk01

medium

# Unfair distribution of points due to price volatility of the `lpToken`.

## Summary
Users who will deposit when the price of the `lpToken` is lower will get relative more points than those who deposit when the price is higher and this will lead to unfair distribution of the points.

## Vulnerability Detail
`SophonFarming` contract just issue reward points based on the amount of `lpToken` deposited and does not take into account the actual value of the `lpToken` at the time of deposit. We are assuming they will fix that 1 ETH can not give the user the some points as 1 DAI, but we must notice that 1 ETH will give the same reward points for the whole duration of the farm. That means that 1 ETH deposited when ETH is at $3800 will give the same reward points as 1 ETH deposited when ETH is at $2000. In this way, the users who will deposit when the price of the `lpToken` is lower will get relative more points than those who deposit when the price is higher and this will lead to unfair distribution of the points.

## Impact
The reward points will be unfairly distributed among the users and the amount commitment of `lpToken` and time will not be a legit representation of the reward points earned. It is, also, possible in some crashes of an `lpToken` that the reward system will break down since someone will be able to get a lot of points with a small amount of `lpToken`.

## Code Snippet
Here is the `_deposit()` function that does not take into account the actual value of the `lpToken` at the time of deposit : 
```solidity
    function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_depositAmount == 0) {
            revert InvalidDeposit();
        }
        if (_boostAmount > _depositAmount) {
            revert BoostTooHigh(_depositAmount);
        }

        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
        updatePool(_pid);

        uint256 userAmount = user.amount;
        user.rewardSettled =
            userAmount *
            pool.accPointsPerShare /
            1e18 +
            user.rewardSettled -
            user.rewardDebt;

        // booster purchase proceeds
        heldProceeds[_pid] = heldProceeds[_pid] + _boostAmount;

        // deposit amount is reduced by amount of the deposit to boost
        _depositAmount = _depositAmount - _boostAmount;

        // set deposit amount
        user.depositAmount = user.depositAmount + _depositAmount;
        pool.depositAmount = pool.depositAmount + _depositAmount;

        // apply the boost multiplier
        _boostAmount = _boostAmount * boosterMultiplier / 1e18;

        user.boostAmount = user.boostAmount + _boostAmount;
        pool.boostAmount = pool.boostAmount + _boostAmount;

        // userAmount is increased by remaining deposit amount + full boosted amount
        userAmount = userAmount + _depositAmount + _boostAmount;

        user.amount = userAmount;
        pool.amount = pool.amount + _depositAmount + _boostAmount;

        user.rewardDebt = userAmount *
            pool.accPointsPerShare /
            1e18;

        emit Deposit(msg.sender, _pid, _depositAmount, _boostAmount);
    }
```
[Link to code](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L574)

## Tool used
Manual code inspection

## Recommendation
Consider using a different mechanism to distribute the reward points that will depend on the amount of `lpToken` deposited. Maybe use a price oracle like [Chainlink](https://docs.chain.link/data-feeds/price-feeds) so to calculate the actual value of the `lpToken` at the time of deposit and then distribute the reward points accordingly.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because users can always optionally call deposit() by pre-converting DAI/sDAI, ETH/stETH, ETH/eTH at their control
