### ISSUE TITLE
samuraii77 - A tricky user can make the pool he is staking in have a significant advantage over others

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#172]
samuraii77

medium

# A tricky user can make the pool he is staking in have a significant advantage over others

## Summary
A tricky user can make the pool he is staking in have a significant advantage over others
## Vulnerability Detail
All of the pools have a particular `startBlock` when they are expected to start generating points for users who stake. 
Upon the first stake after the `startBlock`, this is how the pool gets updated:
```solidity
if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0) {
       pool.lastRewardBlock = getBlockNumber();
       return;
}
```
The `lastRewardBlock` gets set to the current block number and then in the next block, the increase of points per share would be as follows:
```solidity
uint256 blockMultiplier = _getBlockMultiplier(pool.lastRewardBlock, getBlockNumber());
uint256 pointReward = blockMultiplier * _pointsPerBlock * _allocPoint / totalAllocPoint;
pool.accPointsPerShare += pointReward / lpSupply;
pool.lastRewardBlock = getBlockNumber();
```
`blockMultiplier` will be `1e18` as just 1 block passed since the last update.

Now, imagine the following scenario:
1. The current block number is 100 while the `startBlock` is 200
2. Bob, a tricky user, decides to stake in a particular pool and get a significant advantage over every other pool
3. He deposits 1 wei of the pool token at block 100
4. `updatePool()` gets called and returns almost immediately as the block number is less than the lastRewardBlock (startBlock):
```solidity
if (getBlockNumber() <= pool.lastRewardBlock) {
     return;
}
```
5. The deposit function continues running and makes state changes based on the 1 wei deposit amount
6. Then, at block 201, that pool will have a significant advantage over others
7. Bob deposits again, this time an actual amount he wants to lock
8. `updatePool()` gets called and we skip both of those if checks as the `lpSupply` is 1 wei due to Bob's earlier deposit:
```solidity
if (getBlockNumber() <= pool.lastRewardBlock)
if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0)
```
9. Now, the `blockMultiplier` is 100e18 instead of 1e18 giving this pool an initial amount of points per share 100 times larger than every other pool that didn't do this trick and instead waited for the `startBlock` as expected

This allows a user who understands Solidity to have a significant advantage over regular users. He can essentially boost the point rewards for his pool while every other pool would have significantly lower point rewards.
## Impact
A tricky user can make the pool he is staking in have a significant advantage over others
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L574-L624
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L411-L435
## Tool used

Manual Review

## Recommendation
Do not allow deposits before the `startBlock`

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because userAmount isn't updated when user.rewardSettled is assigned. userAmount is updated by the time user.rewardDebt is assigned though
