### ISSUE TITLE
hunter_w3b - Discrepancy in the conversion process between `DAI` and `sDAI`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#174]
hunter_w3b

high

# Discrepancy in the conversion process between `DAI` and `sDAI`

## Summary

In the `SophonFarming` contract allows users to deposit DAI and unstake sDAI, but there's a discrepancy in the conversion process between DAI and sDAI. The issue arises when minting sDAI from DAI, as the resulting shares are worth less than the deposited DAI due to a conversion function (`_daiTOsDai`) that doesn't properly account for the difference in value. Consequently, users receive fewer sDAI than expected, and the surplus DAI remains locked in the contract.

## Vulnerability Detail

The SophonFarming contract allows users to deposit DAI and unstake sDAI in return. The problem is that sDAI is an ERC4626 contract. Dai is the native asset and sDAI is the share.

When minting sDAI in return from Dai, usually, the shares are worth more than the asset, e.g., 1 sDAI : 1.05 Dai.

Since sDAI is already the share, it returns lesser Dai than intended since sDAI::convertToShares() takes in an asset amount and returns the amount of the share.

The user will get back lesser sDAI, and the remaining shares will be stuck in the contract.

```solidity
    function depositDai(uint256 _amount, uint256 _boostAmount) external {
        IERC20(dai).safeTransferFrom(
            msg.sender,
            address(this),
            _amount
        );

        _depositPredefinedAsset(_amount, _amount, _boostAmount, PredefinedPool.sDAI);
    }


    function _depositPredefinedAsset(uint256 _amount, uint256 _initalAmount, uint256 _boostAmount, PredefinedPool _predefinedPool) internal {

        uint256 _finalAmount;

        if (_predefinedPool == PredefinedPool.sDAI) {
            _finalAmount = _daiTOsDai(_amount);
        } else if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _stEthTOwstEth(_amount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _eethTOweEth(_amount);
        } else {
            revert InvalidDeposit();
        }

        // adjust boostAmount for the new asset
        _boostAmount = _boostAmount * _finalAmount / _initalAmount;

        _deposit(typeToId[_predefinedPool], _finalAmount, _boostAmount);
    }



    function withdraw(uint256 _pid, uint256 _withdrawAmount) external {
        if (isWithdrawPeriodEnded()) {
            revert WithdrawNotAllowed();
        }
        if (_withdrawAmount == 0) {
            revert WithdrawIsZero();
        }

        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
        updatePool(_pid);

        uint256 userDepositAmount = user.depositAmount;

        if (_withdrawAmount == type(uint256).max) {
            _withdrawAmount = userDepositAmount;
        } else if (_withdrawAmount > userDepositAmount) {
            revert WithdrawTooHigh(userDepositAmount);
        }

        uint256 userAmount = user.amount;
        user.rewardSettled =
            userAmount *
            pool.accPointsPerShare /
            1e18 +
            user.rewardSettled -
            user.rewardDebt;

        user.depositAmount = userDepositAmount - _withdrawAmount;
        pool.depositAmount = pool.depositAmount - _withdrawAmount;

        userAmount = userAmount - _withdrawAmount;

        user.amount = userAmount;
        pool.amount = pool.amount - _withdrawAmount;

        pool.lpToken.safeTransfer(msg.sender, _withdrawAmount);

        user.rewardDebt = userAmount *
            pool.accPointsPerShare /
            1e18;

        emit Withdraw(msg.sender, _pid, _withdrawAmount);
    }

```

For example:

If a user deposits `10.5` DAI and receives 10 sDAI in return at the exchange rate of 1 sDAI : 1.05 DAI, when they withdraw the 10 sDAI, the remaining 0.5 DAI will be stuck in the contract.

## Impact

The remaining DAI get stuck in the contract,

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L458-L466

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L551-L553

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L854-L858

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L699-L743

## Tool used

Manual Review

## Recommendation

The contract's conversion function `_daiTOsDai` needs to be revised to ensure accurate conversion between DAI and sDAI.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because lpToken, i.e. sDAI is transferred to the user. There's no DAI in the contract.
