### ISSUE TITLE
_karanel - Allows user to deposit into `sDAI` PredefinedPool by calling `depositEth`/`depositWeth`, consuming `DAI` reserves from the contract if present.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#18]
_karanel

medium

# Allows user to deposit into `sDAI` PredefinedPool by calling `depositEth`/`depositWeth`, consuming `DAI` reserves from the contract if present.

## Summary
A user can call `depositEth` or `depositWeth` by passing `_predefinedPool` as `0` (i.e. `PredefinedPool.sDAI`) and consume the contract's DAI reserves, as the user never sent DAI to the contract. This would cause an issue when someone tries to call `withdraw` but is unable to withdraw since there is less DAI available than deposited.

## Vulnerability Detail
Both function `depositEth` and `depositWeth` have this particular conditions. If a user calls any of this functions by passing `_predefinedPool` as `0` (i.e. `PredefinedPool.sDAI`), it'll bypass these conversions and call `_depositPredefinedAsset` to deposit DAI into sDAI pool, with the same amount of ETH sent.

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L509-L513
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L532-L536
```javascript
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
        }
```

## Impact
It may seem like a loss for the particular user and not the protocol (since let's say protocol got 1 ETH but only lost 1 DAI), the issue would arise when a genuine user tries to call `withdraw` but is unable to do so, due to lack of token reserves in the contract. This would also affect pointRewards whenever `updatePool` is called.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L503-L516
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L524-L539

## Tool used

Manual Review

## Recommendation

Revert the transaction if any other value for PredefinedPool is passed.
```diff
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
+       } else {
+           revert InvalidDeposit();
        }
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because user input validation to prevent user mistakes is not considered a valid issue. Additionally, the likelihood of the scenario happening is extremely low

**Comment by Karan9034** [comment]
@mystery0x you are right that user input validation is not considered a valid issue. But this is only if it does not cause a loss of funds. According to the [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid:~:text=User%20input%20validation%3A%20User%20input%20validation%20to%20prevent%20user%20mistakes%20is%20not%20considered%20a%20valid%20issue.%20However%2C%20if%20a%20user%20input%20could%20result%20in%20a%20major%20protocol%20malfunction%20or%20significant%20loss%20of%20funds%20could%20be%20a%20valid%20high.%20Example(Valid)):
> User input validation: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high. [Example(Valid)](https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/47)

Agreed that the likelihood is low, but the impact is High/borderline Medium. This issue should at least be a medium.

**Comment by BiasedMerc** [comment]
> @mystery0x you are right that user input validation is not considered a valid issue. But this is only if it does not cause a loss of funds. According to the [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid:~:text=User%20input%20validation%3A%20User%20input%20validation%20to%20prevent%20user%20mistakes%20is%20not%20considered%20a%20valid%20issue.%20However%2C%20if%20a%20user%20input%20could%20result%20in%20a%20major%20protocol%20malfunction%20or%20significant%20loss%20of%20funds%20could%20be%20a%20valid%20high.%20Example(Valid)):
> 
> > User input validation: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high. [Example(Valid)](https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/47)
> 
> Agreed that the likelihood is low, but the impact is High/borderline Medium. This issue should at least be a medium.

This is invalid. If a user tries to pass in the sDAI pool in depositETH() the function will revert during the _daiTOsDai() conversion. The contract never holds DAI only sDAI as all transfered DAI is immediately converted through _daiTOsDai().

When _daiTOsDai() attempts to convert the amount that is passed through msg.value which is in ETH, there will not be enough DAI to convert and it will revert.

Also your issue says the impact is:

DAI reserves get consumed, but there are no DAI reserves.
User cannot withdraw DAI, but users only withdraw sDAI

Both of the outlined impacts in your issue are incorrect

**Comment by mystery0x** [comment]
@BiasedMerc explains it well.

**Comment by Karan9034** [comment]
@mystery0x My issue states:
1. DAI reserves (if present) get consumed, which is valid as DAI could be sent by anyone to the contract.
2. Causes loss of user's ETH and not the protocol.
3. Affects the pointRewards as it will incorrectly track the deposited ETH/WETH as DAI.

The function only reverts if no DAI is present in the contract, otherwise causes loss of funds for the user. Moreover, you cannot say that it is invalid input or user mistake as `PredefinedPool.sDAI` is a valid value for the `_predefinedPool` parameter in the `depositEth` and `depositWeth` functions. This makes it a valid medium as it causes loss of funds according to the rules:

> Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

> User input validation: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high.


Also I agree that `User cannot withdraw DAI, but users only withdraw sDAI` is incorrect and a mistake on my part.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/f0b82fd83a5d85eb8dc7ba2bbce2d49fefb326a4

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
