### ISSUE TITLE
no - Bypass  pool check in `depositEth`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#180]
no

medium

# Bypass  pool check in `depositEth`

## Summary
Bypass  pool check in `depositEth`
## Vulnerability Detail
There are only two checks(PredefinedPool.wstETH and PredefinedPool.weETH) for pool. Miss else pool check  in `depositEth` Then other pool can bypass the check.
```javascript
 function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
        if (msg.value == 0) {
            revert NoEthSent();
        }

        uint256 _finalAmount = msg.value;
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
        }
@>      //miss else check 
        _depositPredefinedAsset(_finalAmount, msg.value, _boostAmount, _predefinedPool);
    }
```
The same issue exists in depositWeth.
## Impact
There is a pool that can be used to bypass checks, posing a potential risk of funds being stolen.
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L503
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L524
## Tool used

Manual Review

## Recommendation
```diff
-           }
+           } else {
+               revert InvalidDeposit();
+           }
```

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because user input validation to prevent user mistakes is not considered a valid issue. Additionally, the likelihood of the scenario happening is extremely low

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/f0b82fd83a5d85eb8dc7ba2bbce2d49fefb326a4

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
