### ISSUE TITLE
befree3x - Missing pool type check on `SophosFarming::depositEth` and `SophosFarming::depositWeth` could lead a user to loose `ETH` funds forever

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#181]
befree3x

medium

# Missing pool type check on `SophosFarming::depositEth` and `SophosFarming::depositWeth` could lead a user to loose `ETH` funds forever

## Summary

Missing pool type check on `SophosFarming::depositEth` and `SophosFarming::depositWeth` could lead a user to deposit `ETH` to the farming contract but his points and rewards are counted for deploying `DAI`, while having no possibility to withdraw the deposited `ETH` amount.

## Vulnerability Detail

The functions `depositEth` and `depositWeth` allow a user to deposit `ETH` and `WETH` respectively.
However, the `_predefinedPool` is provided by the end user, as described below.

```javacscript

@>    function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
        if (msg.value == 0) {
            revert NoEthSent();
        }

        uint256 _finalAmount = msg.value;
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount); // e converting eth to eEth
        }

        _depositPredefinedAsset(_finalAmount, msg.value, _boostAmount, _predefinedPool);
    }

```

if the `_predefinedPool` parameter has the value `PredefinedPool.sDAI` instead of `PredefinedPool.wstETH` or `PredefinedPool.weETH`, the user actually deposits `ETH` to the `SophonFarming` contract but her/his deposit records, e.g. points and rewards, are updated on the `sDAI` pool. In addition, there will be no record of deploying `ETH` for her/him after such operation, hence, there will be no possible withdrawal of the deposited `ETH` amount.

Links to the affected code:
- `depositEth` function: https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L503
- `depositWeth` function: https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L524

## Impact

A user could deposit `ETH` but his points and rewards are wrongly calculated for the `sDAI` pool. As a consequence, he could never withdraw the deposited `ETH` from the protocol.

## Code Snippet
Scenario:
1. An attacker donates an amount of DAI to the SophonFarming contract beforehand (or front-run the user transaction in step 2)
2. A user deposits `ETH` to the `sDAI` pool by mistake using the function `depositEth`
3. He tries to withdraw the deposited `ETH` without success.

The following proof of code can be appended to the file `SophonFarming.t.sol`. Run the test with the command: `forge test --mt test_DepositEth_NotBoosted_To_sDAI_Pool_Cant_Withdraw_ETH_Afterward`.

<details>
<summary>Code</summary>

```javascript

function test_DepositEth_NotBoosted_To_sDAI_Pool_Cant_Withdraw_ETH_Afterward() public {
        address attacker = makeAddr("attacler");
        uint256 amountDaiToDeposit = 100e18;

        deal(address(dai), attacker, amountDaiToDeposit); // the attacker has 100 DAI

        // 1. The attacker donates 100 DAIs to the sophon farming contract
        vm.startPrank(attacker);
        dai.transferFrom(attacker, address(sophonFarming), amountDaiToDeposit);
        vm.stopPrank();

        // 2. account1 want to deposit 100 ETH to the farming contract
        // the attacker just needs amountDaiToDeposit to be bigger or equal than amountETHToDeposit to reproduce the issue
        uint256 amountETHToDeposit = 100e18;
        vm.deal(account1, amountETHToDeposit);

        vm.startPrank(account1);
        uint256 wsthDepositedAmount = WstETHRate(StETHRate(amountETHToDeposit));
        // NOTE: account1 deposits ETH but puts the wrong pool type
        sophonFarming.depositEth{value: amountETHToDeposit}(0, SophonFarmingState.PredefinedPool.sDAI);
        assertEq(address(account1).balance, 0); // account1's ETH balance is now zero
        vm.stopPrank();

        // 3. acccount1 wants to withdraw his 100 ETH deposited but he can't
        uint256 wstETHPoolId = sophonFarming.typeToId(SophonFarmingState.PredefinedPool.wstETH);
        SophonFarmingState.UserInfo memory userInfo = getUserInfo(wstETHPoolId, account1);

        vm.startPrank(account1);
        vm.expectRevert(abi.encodeWithSelector(SophonFarming.WithdrawTooHigh.selector, userInfo.depositAmount));
        // The withdraw reverts as the current ETH deposited by account1 in the protocol's point of view is 0,
        // instead of 100 ETH as the user expected
        sophonFarming.withdraw(wstETHPoolId, amountETHToDeposit);
        assertFalse(userInfo.depositAmount == amountDaiToDeposit);
        assertEq(userInfo.depositAmount, 0);

        // He now have a positive amount of sDAI recorded in the sDai pool
        // despite the fact that he never deposit DAI to the SophonFarming contract
        uint256 sDaiPoolId = sophonFarming.typeToId(SophonFarmingState.PredefinedPool.sDAI);
        SophonFarmingState.UserInfo memory userInfoInsDaiPool = getUserInfo(sDaiPoolId, account1);
        assertTrue(userInfoInsDaiPool.depositAmount > 0);

        vm.stopPrank();
}

```
</details>

Note that the same issue can happen for a user depositing `WETH` to the `sDAI` pool by mistake using the function `depositWeth`. The deposited `WETH` fund will get locked in the `SophonFarming` contract and he won't be able to retrieve it.

## Tool used

Manual Review

## Recommendation

It's recommended to add a safeguard in both functions `depositEth` and `depositWeth` to prevent a user from depositing `ETH` or `WETH` into the `sDAI` pool.
Consider adding the following changes to the file `SophonFarming.sol`:

```diff

function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
...
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount); // e converting eth to stEth
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount); // e converting eth to eEth
+       } else {
+           revert InvalidDeposit();
+       }

...
}

function depositWeth(uint256 _amount, uint256 _boostAmount, PredefinedPool _predefinedPool) external {
...
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
+       } else {
+           revert InvalidDeposit();
+       }
...
}

```

The two test cases below can also be appended to the file `SophonFarming.t.sol` to prevent future regression.

<details>
<summary>Code</summary>

```javascript

function test_DepositEth_To_sDAI_Pool_Revert() public {
        uint256 amountETHToDeposit = 100e18;
        vm.deal(account1, amountETHToDeposit);

        vm.startPrank(account1);
        uint256 wsthDepositedAmount = WstETHRate(StETHRate(amountETHToDeposit));
        vm.expectRevert(SophonFarming.InvalidDeposit.selector);
        sophonFarming.depositEth{value: amountETHToDeposit}(0, SophonFarmingState.PredefinedPool.sDAI);
        vm.stopPrank();
    }

    function test_DepositWeth_To_sDAI_Pool_Revert() public {
        uint256 amountWETHToDeposit = 100e18;

        vm.startPrank(account1);
        vm.deal(account1, amountWETHToDeposit);
        weth.deposit{value: amountWETHToDeposit}();
        assertEq(weth.balanceOf(account1), amountWETHToDeposit);

        weth.approve(address(sophonFarming), amountWETHToDeposit);
        vm.expectRevert(SophonFarming.InvalidDeposit.selector);
        sophonFarming.depositWeth(amountWETHToDeposit, 0, SophonFarmingState.PredefinedPool.sDAI);
        vm.stopPrank();
    }


```

</details>

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because user input validation to prevent user mistakes is not considered a valid issue. Additionally, the likelihood of the scenario happening is extremely low

**Comment by BiasedMerc** [comment]
Escalate

Sherlock rules state:
>User input validation: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input >could result in a major protocol malfunction or significant loss of funds could be a valid high. [Example(Valid)](https://>github.com/sherlock-audit/2022-10-illuminate-judging/issues/47)

There are 3 different pre-determined pools users can utilise to deposit funds to be converted. A user providing any of these 3 pre-determined pools when depositing `ETH` or `WETH` is a valid scenario. This reasonable user mistake of providing the `sDAI` pool would then lead to them losing a large amount of funds:

User deposits `1 ETH` providing the `sDai` pool as an input expecting their `ETH` to be converted to `sDAI`, a malicious griefer front-runs with a small deposit of `1 DAI`, meaning the griefer has very minimal cost for this attack. With `1 DAI` the griefer makes the user lose `1 ETH`, which is 3000x the value of the griefers attack. 
OR
If there is any `DAI` already in the pool then there is no need for a griefer to front-run the user. Just a deposit of `DAI` at any point will lead to this loss scenario occuring and there is no way for an `Admin` to transfer out any `DAI` sitting in the contract, meaning this scenario can execute reasonably.

As the protocol has 3 pre-defined pools there should be effective protections to ensure all deposits are routed correctly and revert if one of the pre-defined pools is provided through the wrong deposit function, therefore this issue is a valid medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Sherlock rules state:
> >User input validation: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input >could result in a major protocol malfunction or significant loss of funds could be a valid high. [Example(Valid)](https://>github.com/sherlock-audit/2022-10-illuminate-judging/issues/47)
> 
> There are 3 different pre-determined pools users can utilise to deposit funds to be converted. A user providing any of these 3 pre-determined pools when depositing `ETH` or `WETH` is a valid scenario. This reasonable user mistake of providing the `sDAI` pool would then lead to them losing a large amount of funds:
> 
> User deposits `1 ETH` providing the `sDai` pool as an input expecting their `ETH` to be converted to `sDAI`, a malicious griefer front-runs with a small deposit of `1 DAI`, meaning the griefer has very minimal cost for this attack. With `1 DAI` the griefer makes the user lose `1 ETH`, which is 3000x the value of the griefers attack. 
> OR
> If there is any `DAI` already in the pool then there is no need for a griefer to front-run the user. Just a deposit of `DAI` at any point will lead to this loss scenario occuring and there is no way for an `Admin` to transfer out any `DAI` sitting in the contract, meaning this scenario can execute reasonably.
> 
> As the protocol has 3 pre-defined pools there should be effective protections to ensure all deposits are routed correctly and revert if one of the pre-defined pools is provided through the wrong deposit function, therefore this issue is a valid medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Karan9034** [comment]
Flagging #18 as dup and agree with the escalation.

**Comment by Autosaida** [comment]
There are many other issues that duplicate this one, such as #154 and #112. I agree that this would be a valid issue. Although it relates to user input, regardless of whether it's due to an attacker frontrunning or another erroneous transfer that results in the contract having a DAI balance, it could lead to a permanent loss of ETH when users use incorrect parameters. Although the likelihood is low, the potential severity is high, so I consider this a medium issue. Looking forward to and curious about the final judge results :)

**Comment by Karan9034** [comment]
Agreed. Also I would like to point out that nowhere in the docs or the natspec it was mentioned that `ETH`/`WETH` can **only** be deposited to `wstETH` and `weETH` pools, and not the `sDAI` pool. We are only assuming that entering `sDAI` pool is incorrect user input. `sDAI` is also a valid value for the `_predefinedPool` parameter, and we should assume it is a valid input. On entering `sDAI`, the function should work correctly (either convert ETH to DAI and deposit to sDAI pool, or otherwise revert). But clearly if any malicious user sends `1 DAI` to the contract (front-running or a simple transfer), they can block upto `1 ETH` of future deposits to `sDAI` pool with no way to recover the ETH or stop this particular scenario.

**Comment by mystery0x** [comment]
The protocol neither suffers a major protocol malfunction nor significant loss of funds. This is equivalent to users sending in more ETH than required in a payable function and the protocol isn't refunding the excess.

**Comment by befree3x** [comment]
Agreed that the protocol does not lost any amount of funds, but shouldn't the protocol protect users from loosing significant  amount of ETH for such trivial mistake. This could increase trust and resilience of the protocol in user's point of view.

**Comment by WangSecurity** [comment]
I agree that it would increase trust and resilience of the protocol from the user's point of view. But, the rules clearly say:

> User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high

As's already mentioned, the only one harmed here is the user and it's their responsibility to send the correct asset to the correct pool.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by Karan9034** [comment]
@WangSecurity it is never mentioned which asset is to be deposited to which pool. How is depositing ETH/WETH to sDAI pool incorrect?

**Comment by WangSecurity** [comment]
@Karan9034 The reason is that sDAI has DAI as an underlying token, not ETH or WETH. The same as to receive the staked ETH you need to deposit ETH and not DAI. 

Regardless of that, the rule still applies correctly. The user harms themselves with the input values they submit.

Hence, the decision remains the same, reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BiasedMerc](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/181/#issuecomment-2143411566): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/f0b82fd83a5d85eb8dc7ba2bbce2d49fefb326a4

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
