### ISSUE TITLE
tives - accPointsPerShare is set according to previous pool.amount

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#183]
tives

medium

# accPointsPerShare is set according to previous pool.amount

## Summary
accPointsPerShare is set according to previous pool.amount.

## Vulnerability Detail
In withdraw, deposit, and increaseBoost, the pool is updated with `updatePool`. In there, `accPointsPerShare` is set according to `pool.amount`

However, `pool.amount` is set after calling `updatePool`. Therefore, calculations using `accPointsPerShare` will use the wrong value.

## Impact
If we are `withdrawing`, then the pool `accPointsPerShare` be lower than actual. This is because pointReward is divided by lpSupply(pool.amount)

User is rewarded less points than her deposit is worth.

IncreaseBoost and Deposit have the same issue, but with different impact.

## Code Snippet
```solidity
function withdraw(uint256 _pid, uint256 _withdrawAmount) external {
    if (isWithdrawPeriodEnded()) {
        revert WithdrawNotAllowed();
    }
    if (_withdrawAmount == 0) {
        revert WithdrawIsZero();
    }

    PoolInfo storage pool = poolInfo[_pid];
    UserInfo storage user = userInfo[_pid][msg.sender];
    updatePool(_pid);

    ...

    pool.amount = pool.amount - _withdrawAmount;

    pool.lpToken.safeTransfer(msg.sender, _withdrawAmount);

    user.rewardDebt = userAmount *
        pool.accPointsPerShare /
        1e18;

```

https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol/#L709

https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol/#L737

## Tool used
Manual Review

## Recommendation

Set the `pool.amount` before calling `updatePool`.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because doing it as suggested by the mitigation is going to inflate user.rewardSettled when depositing
