### ISSUE TITLE
0xShoonya - Wrong reward points calculation in `SophonFarming.sol` contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#187]
0xShoonya

high

# Wrong reward points calculation in `SophonFarming.sol` contract

## Summary
When adding a new `pool` to the `SophonFarming.sol` using the `add` function with `_withUpdate` set to `false`, the existing pools are not updated. Consequently, only `totalAllocPoint` is updated, leading to a situation where the share of old pools is not accurately reflected in subsequent updates. This results in incorrect computation of user yields, which will consistently be smaller than expected.

## Vulnerability Detail
[SophonFarming.sol#L153](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L153)
The `add` function allows adding a new pool (`_lpToken`) with a specified allocation point (`_allocPoint`). The `_withUpdate` parameter determines whether all pools should be updated when adding the new pool.

```js
  function add(uint256 _allocPoint, address _lpToken, string memory _description, bool _withUpdate) public onlyOwner returns (uint256) {

``` 
If `_withUpdate` is set to false, the current implementation does not update the existing pools. This oversight means that while `totalAllocPoint` is updated to include the allocation points of the new pool, the accumulated yield for the old pools are not recalculated based on the new `totalAllocPoint`. As a result, during the next yield distribution, the share of yields for old pools will be smaller, leading to incorrect user yields.

Ultimately, yields in this contract are intended to be linearly distributed over time. Adding a new pool changes the rate at which yields are distributed across all pools. Therefore, it is necessary to accrue the yields that each pool has generated up to that point before changing the rate at which yields will be distributed.
## Impact
Incorrect user yields for old pools
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L153-L187
## Tool used
Manual Review

## Recommendation
Remove the `_withUpdate` parameter and always call `massUpdatePools` when adding new pools to ensure accurate yield distribution. This will ensure that all pools are updated to the latest state before adding a new one, thereby preventing any discrepancies in yield calculations.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/6d117397d57a39a865cee0621cabf9154fb6fd71

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
