### ISSUE TITLE
Audinarey - bridged funds will be stuck without a way to withdraw.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#192]
Audinarey

high

# bridged funds will be stuck without a way to withdraw.

## Summary
Users can call `bridgePool(...)` to deposit funds to an L2 contract. Although the `_l2TxGasLimit` is specified, but the `_l2TxGasPerPubdataByte` is hardcoded to 0 and as such the bridged funds will get stuck without a way to withdraw. This means that gas is not sent with the transaction to the L2 for the execution of the deposit on the L2 and as such the deposit may get stuck in the L2 bridge contract.

```solidity
File: SophonFarming.sol
748:     function bridgePool(uint256 _pid) external {
...
764:         // TODO: change _refundRecipient, verify l2Farm, _l2TxGasLimit and _l2TxGasPerPubdataByte
765:         // These are pending the launch of Sophon testnet
766:         bridge.deposit(
767:             pool.l2Farm,            // _l2Receiver
768:             address(lpToken),       // _l1Token
769:             depositAmount,          // _amount
770             200000,                 // _l2TxGasLimit
771:   @>        0,                      // _l2TxGasPerPubdataByte
772:             owner()                 // _refundRecipient
773:         );

```

## Impact
Funds sent via bridge will get stuck without actually depositing in the L2 contract

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L748-L775

## Tool used

Manual Review

## Recommendation
Don`t hard code the `_l2TxGasPerPubdataByte` value in the `bridgePool(...)` function

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because bridge logic not implemented and not covered by this audit

**Comment by Audinarey** [comment]
Escalate

> invalid because bridge logic not implemented and not covered by this audit

The codebase is the source of truth in this case, the functionality in question is in scope of this audit and the comments gives us pointers as to the intended purpose of the fuction and its parameters.


> III. Sherlock's standards:
Hierarchy of truth: If the protocol team provides no specific information, the default rules apply (judging guidelines).

> If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.

1) 
```solidity
    /**
@>   * @notice Permissionless function to allow anyone to bridge during the correct period
     * @param _pid pid to bridge
     */
    function bridgePool(uint256 _pid) external {

        bridge.deposit(
            pool.l2Farm,            // _l2Receiver
            address(lpToken),       // _l1Token
            depositAmount,          // _amount
            200000,                 // _l2TxGasLimit
    @>      0,                      // _l2TxGasPerPubdataByte
            owner()                 // _refundRecipient
        );
```

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> > invalid because bridge logic not implemented and not covered by this audit
> 
> The codebase is the source of truth in this case, the functionality in question is in scope of this audit and the comments gives us pointers as to the intended purpose of the fuction and its parameters.
> 
> 
> > III. Sherlock's standards:
> Hierarchy of truth: If the protocol team provides no specific information, the default rules apply (judging guidelines).
> 
> > If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.
> 
> 1) 
> ```solidity
>     /**
> @>   * @notice Permissionless function to allow anyone to bridge during the correct period
>      * @param _pid pid to bridge
>      */
>     function bridgePool(uint256 _pid) external {
> 
>         bridge.deposit(
>             pool.l2Farm,            // _l2Receiver
>             address(lpToken),       // _l1Token
>             depositAmount,          // _amount
>             200000,                 // _l2TxGasLimit
>     @>      0,                      // _l2TxGasPerPubdataByte
>             owner()                 // _refundRecipient
>         );
> ```
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
Please see sponsor's comment on https://github.com/sherlock-audit/2024-05-sophon-judging/issues/147 that's similarly reported to your report:

"bridge is not implemented yet. this is just a marketing stub. we will have separate audit for the bridge when we develop it"

**Comment by Audinarey** [comment]
Sponsor's comment does not hold water in this case considering sherlock rules

> If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.

Market stub or not, The rule applies here

**Comment by 7kyuske** [comment]
"Any bridging related code is considered out of scope" 

It is clearly stated in the README Q&A that bridging code is OOS.

**Comment by Audinarey** [comment]
@mystery0x I await your response

**Comment by WangSecurity** [comment]
As correctly mentioned above, the README clearly says:

> Any bridging related code is considered out of scope

In the additional audit info question.

Planning to reject the escalation and leave the issue as it is, since it's out of scope.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Audinarey](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/192/#issuecomment-2144739722): rejected
