### ISSUE TITLE
Chuchulev - Missing zero address check in Upgradeable

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#2]
Chuchulev

medium

# Missing zero address check in Upgradeable

## Summary
`Upgradeable::replaceImplementation` function is missing a zero address check.

## Vulnerability Detail
The contract allows the owner to set the implementation address to any value without performing any validation. This could potentially allow the owner to set the address to a malicious contract or the zero address.

## Impact
A lack of zero address checks could expose the contract to security risks, such as attackers sending tokens to the zero address, causing a loss of funds or manipulating the contract's functionality. Users rely on the security and integrity of smart contracts to interact with their funds. If zero-address validation is not performed, users' funds could be at risk of being sent to the zero address, rendering them irretrievable.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/proxies/Upgradeable.sol#L11-L13

## Tool used
Manual review + Slither

## Recommendation
To mitigate these impacts, it's crucial to implement zero address checks in the `Upgradeable` contract. Here's how this can be incorporated in the `replaceImplementation` function:

```javascript
error Upgradeable__InvalidImplementationAddress();

function replaceImplementation(address impl_) public onlyOwner {
        if (impl_ == address(0)) {
            revert Upgradeable__InvalidImplementationAddress();
        }
        implementation = impl_;
    }
```

This addition ensures that the new implementation address cannot be the zero address, thus preventing unintended behavior, mitigating security risks, safeguarding user funds, complying with business logic, and preventing loss of ownership.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because of zero address input validation
