### ISSUE TITLE
petro1912 - `depositEth` and `depositWeth` allows to deposit sDai pool.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#23]
petro1912

medium

# `depositEth` and `depositWeth` allows to deposit sDai pool.

## Summary
`depositEth` and `depositWeth` functions mints `wstEth` and `weEth` from eth and then sends it to predefined pools for point rewards.
But `depositEth` and `depositWeth` functions allows users to deposit sDAI using their eth balance.

## Vulnerability Detail
`depositEth` and `depositWeth` functions don't check if `_predefinedPool` is not sDAI.
```solidity
function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
        if (msg.value == 0) {
            revert NoEthSent();
        }

        uint256 _finalAmount = msg.value;
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
        }

        _depositPredefinedAsset(_finalAmount, msg.value, _boostAmount, _predefinedPool);
 }
```
if user takes `_predefinedPool` as `sDAI` by mistake, it is not reverted.
Therefore, user deposits `eth`, or `weth`, but `_depositPredefinedAsset` internal function converts `dai` to `sDai` and then calculates points for sDAI pool.
Then `dai` balance is not increased but `dai` will be converted to `sDAI`.
And `eth` supply is increased but point rewards will not be accrued for wstEth/weEth pool.

## Impact
It impacts correct points calculation accrued between all predefined pools.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L503-L516
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L524-L539

## Tool used

Manual Review

## Recommendation
`depositEth`, and `depositWeth` functions should revert for PredefinedPool.sDAI.
```solidity
function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
        if (msg.value == 0) {
            revert NoEthSent();
        }

        uint256 _finalAmount = msg.value;
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
        }
++      else {
++          revert InvalidDeposit();
++      }
        _depositPredefinedAsset(_finalAmount, msg.value, _boostAmount, _predefinedPool);
}
```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because user input validation to prevent user mistakes is not considered a valid issue. Additionally, the likelihood of the scenario happening is extremely low

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/f0b82fd83a5d85eb8dc7ba2bbce2d49fefb326a4

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
