### ISSUE TITLE
bronze_pickaxe - Users depositing rebase tokens will lose points and funds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#25]
bronze_pickaxe

medium

# Users depositing rebase tokens will lose points and funds

## Summary
Usage of rebase tokens will lead to lost points and funds.
## Vulnerability Detail
A user can deposit rebase tokens like`stETH` and `eETH` into `SophonFarming.sol` using the `deposit*` functions. We will be focussing on `stETH` in this report but the same applies to `eETH`.

A user can deposit `stETH` using`depositStEth()`:
[SophonFarming.sol#L473-L481)](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L473-L481)
```javascript
    function depositStEth(uint256 _amount, uint256 _boostAmount) external {
        IERC20(stETH).safeTransferFrom(
            msg.sender,
            address(this),
            _amount
        );

        _depositPredefinedAsset(_amount, _amount, _boostAmount, PredefinedPool.wstETH);
    }
```

As per the [Lido docs](https://help.lido.fi/en/articles/5230610-what-is-steth):
```md
stETH is a transferable rebasing utility token representing a share of the total ETH staked 
through the protocol, which consists of user deposits and staking rewards. 
Because stETH rebases daily, it communicates the position of the share daily.
The mechanism which updates the stETH balances every day is called a “rebase”. 
Every day at 12PM UTC the amount of stETH in your address will increase with the current APR. 
```

`stETH` is a rebase token, which means that overtime, the balance of a user increases with the current APR.
This is a problem in the current iteration of the project.

## Impact
- Alice deposits `1000e18 stETH` for 30 days to earn points.
- During these 30 days, Alice will only earn points on the initial deposited `1000e18 stETH`, even though that the `1000e18 stETH` has increased over the 30 days.
- Furthermore, when Alice decides to withdraw, she will only be able to withdraw `1000e18 stETH`, even though her initial deposit has increased due to the rebases during the 30 days.
    - At the time of writing, Alice will have lost ~10k USD using [Lido's Rewards Calculator](https://lido.fi/ethereum).

Note that the same applies to the usage of `eETH`.

## Code Snippet
```javascript
    function depositStEth(uint256 _amount, uint256 _boostAmount) external {
        IERC20(stETH).safeTransferFrom(
            msg.sender,
            address(this),
            _amount
        );

        _depositPredefinedAsset(_amount, _amount, _boostAmount, PredefinedPool.wstETH);
    }
```
## Tool used
Manual Review

## Recommendation
Handle rebase tokens differently or don't use them at all.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because that's the trade off for point farming. However, stETH rebases based off its value against ETH
