### ISSUE TITLE
bronze_pickaxe - Honest users can have their whole deposit stolen.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#26]
bronze_pickaxe

high

# Honest users can have their whole deposit stolen.

## Summary
Negative rebases can drain the whole deposit of honest users.

## Vulnerability Detail
The protocol uses `stETH`, which can negative rebase as per [Lido.fi docs](https://docs.lido.fi/integrations/aave/specification/).
This becomes a problem when a negative rebase happens because everyone will be able to claim their full deposit amount, leaving the people who have not claimed left with way less than the negative percentage that had been negatively rebased.

## Impact
- 10 users all deposit `10e18 stETH` each, total deposit is `100e18 stETH`.
- A negative rebase happens of `-10%`, which means the total deposit is now `90e18 stETH`.
- The first 9 users are all able to withdraw their original `10e18 stETH` deposit each.
- The last user will be left with nothing, losing `10e18 stETH`.

## Code Snippet
[SophonFarming.sol#L473-L481](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L473-L481)
```javascript
    function withdraw(uint256 _pid, uint256 _withdrawAmount) external {
        ....
    }
```

## Tool used

Manual Review

## Recommendation
Track the balances of the users dynamically.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the 100 stETH is still there 1:1 via wstETH. Users then decide when/how to convert it back to ETH at their discretion
