### ISSUE TITLE
Naresh - function massUpdatePools() is susceptible to DoS with block gas limit

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#28]
Naresh

medium

# function massUpdatePools() is susceptible to DoS with block gas limit

## Summary

`massUpdatePools()` is a public function and it calls the `updatePool()` function for the length of `poolInfo`. Hence, it is an unbounded loop, depending on the length of `poolInfo`. If `poolInfo.length` is big enough, [block gas limit](https://consensys.github.io/smart-contract-best-practices/attacks/denial-of-service/#dos-with-block-gas-limit) may be hit.

## Vulnerability Detail

```solidity
 function massUpdatePools() public {
        uint256 length = poolInfo.length;
        for(uint256 pid = 0; pid < length;) {
            updatePool(pid);
            unchecked { ++pid; }
        }
    }
```
if new pools continue to be added to this contract, the `poolInfo.length` will continue to grow and this function will eventually be unusable due to excessive gas usage.

## Impact

The `massUpdatePools()` function will eventually be unusable due to excessive gas usage.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L399-L405

## Tool used

Manual Review

## Recommendation

Make the contract capable of removing unnecessary or ended pools to reduce the loop round in the `massUpdatePools()` function. or
Limit the max number of loop iterations to prevent hitting block gas limit.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the array length is controlled by the trusted admin/owner. Currently, there are only 3 elements in poolInfo
