### ISSUE TITLE
Bauchibred - Leak of funds due to the swapping strategy Sophon uses for ETH/WETH when depositing to the `wstETH` PredefinedPool

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#33]
Bauchibred

high

# Leak of funds due to the swapping strategy Sophon uses for ETH/WETH when depositing to the `wstETH` PredefinedPool

## Summary

Sophon currently hardcodes how it converts either of deposited WETH/ETH to stETH in `Sophon#_ethTOstEth()`, however this method would lead to loss of funds for protocol and extensively users since the `_ethTOstEth()` is called via [depositEth()](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L510) and [depositWeth](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L533).

This is because the `stETH.submit` method of converting ETH is suboptimal in the case where `stETH` is cheaper in the curve pool, which makes this submission [**at least** a medium by the judging guidelines](https://docs.sherlock.xyz/audits/judging/judging#v.-how-to-identify-a-medium-issue), since it satisfies more than the below:

> 1. Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.
> 2. Breaks core contract functionality, rendering the contract useless or leading to loss of funds.

NB: In this case we are sure the required is going to be the case for more than 90% of the lifetime of the protocol as has been historically proven.

## Vulnerability Detail

Both [depositEth()](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L510) and [depositWeth](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L533) query `_ethTOstEth()` in the case where the predefined pool to submit to is `PredefinedPool.wstETH`.

Now here is the implementation of `_ethTOstEth()` https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L808-L813

```solidity
    function _ethTOstEth(uint256 _amount) internal returns (uint256) {
        // submit function does not return exact amount of stETH so we need to check balances
        uint256 balanceBefore = IERC20(stETH).balanceOf(address(this));
        IstETH(stETH).submit{value: _amount}(address(this));
        return (IERC20(stETH).balanceOf(address(this)) - balanceBefore);
    }
```

Evidently, the conversion is done via querying `stETH.submit()` however this is not the most optimal approach and in some cases would lead to receiving less amount of `stETH` for deposited eth if protocol would have just gotten `stETH` from a pool instead.

**In most cases** stETH is always cheaper than ETH, see the [Chainlink Oracle](https://data.chain.link/arbitrum/mainnet/crypto-eth/steth-eth), as at the time of writing this report, the going rate is 0.9995 ETH / stETH.

However, the strategy in Sophon currently is to always wrap ETH to stETH by depositing it directly into the Lido Contract as shown in the snippet for `_ethTOstEth` above, which means that the strategy is inherently taking some loss (ETH price vs stETH price) on each deposit.

Here is the data from a research [GalloDaSballo](https://x.com/GalloDaSballo) made on the historical prices of the Chainlink prices for ETH / stETH up until may 2023: https://docs.google.com/spreadsheets/d/1iPEuOtCHt39GkeO-R-y1EyFMxKJbNKS-8ze3WqdiVLk/edit#gid=473732970. With the `AsETH` tab showing the rate in ETH.

Now let's use data from a 2 weeks set of the on-chain price updates for the feed from mid/late July as was done in the same research, source to full two weeks dataset: https://docs.google.com/spreadsheets/d/1iPEuOtCHt39GkeO-R-y1EyFMxKJbNKS-8ze3WqdiVLk/edit#gid=473732970

Here is a scrapped table from the on-chain data:
| roundId | answer | As ETH | LOSS IN BPS | startedAt | updatedAt | answeredInRound |
| -------------------- | ------------------ | ------------ | ----------- | ---------- | ---------- | -------------------- |
| 18446744073709551726 | 998550934081305700 | 0.9985509341 | 14.49065919 | 1687725027 | 1687725027 | 18446744073709551726 |
| 18446744073709551761 | 9.98847E+17 | 0.99884668 | 11.5332 | 1690749851 | 1690749851 | 18446744073709551761 |
| 18446744073709551730 | 998958688800485800 | 0.9989586888 | 10.413112 | 1688070676 | 1688070676 | 18446744073709551730 |
| 18446744073709551732 | 998988324489792200 | 0.9989883245 | 10.1167551 | 1688243534 | 1688243534 | 18446744073709551732 |
| 18446744073709551733 | 998988336918386800 | 0.9989883369 | 10.11663082 | 1688329961 | 1688329961 | 18446744073709551733 |
| 18446744073709551724 | 999064611648799700 | 0.9990646116 | 9.353883512 | 1687552189 | 1687552189 | 18446744073709551724 |
| 18446744073709551743 | 9.99093E+17 | 0.99909267 | 9.0733 | 1689194182 | 1689194182 | 18446744073709551743 |

Evidently, the strategy is locking in a loss of up to `15 BPS` just in depositing, now since the Swap Fee on Mainnet is 1 BPS this is 15 times more than necessary.

If we take into account historical data it's not uncommon for stETH to have higher price changes even more than 130 BPS as linked above, which has also been the case in the past year too, infact from the the [Chainlink Oracle](https://data.chain.link/arbitrum/mainnet/crypto-eth/steth-eth) we can see that 18 days ago the difference showcases a loss of ~20 BPS, as the price was 0.998

![source](https://private-user-images.githubusercontent.com/107410002/332856471-b4d5ec0d-0155-4845-ac90-90048199a57d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTEyOTYsIm5iZiI6MTcxNjM5MDk5NiwicGF0aCI6Ii8xMDc0MTAwMDIvMzMyODU2NDcxLWI0ZDVlYzBkLTAxNTUtNDg0NS1hYzkwLTkwMDQ4MTk5YTU3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNTE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWU0NjZhNWVkNDk2ZjhlYzYyZDM0ZWM0YmM0Mzc5YWRmZmM0MTk4ZmMyNDM1YmU3NWU0Y2NiMmFhN2MwODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hiskBnajEVqjhV0uigu3l_Fqt8DDjZ8UzFiYe3RYjVk)

Conclusively, even more disparity could occur and historical data showcases that in more than 90 cases out of 100 the price of stETH is less than that of ETH.

## Impact

The strategy Sophon currently uses to wrap ETH/WETH to stETH takes on losses in almost all cases since the price of stETH is less than that of ETH most times, cause it does this by depositing the ETH directly into the Lido Contract as shown in the snippet for `_ethTOstEth` above, would be key to note that no slippage parameter is passed on via [depositEth()](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L507) and [depositWeth](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L529) which would mean that there isn't even a method to prevent the swap in the case where the disparity is non-acceptable for user/protocol.

Now, considering we are sure the required external condition is going to be the case for more than 90% of the lifetime of the protocol as has been historically proven with the disparity in price between STETH and ETH, this is submitted as high as it satisfies the condition for [high severity](https://docs.sherlock.xyz/audits/judging/judging#iv.-how-to-identify-a-high-issue).

> ## How to identify a high issue:
> 1. Definite loss of funds without (extensive) limitations of external conditions. 

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L808-L813

## Tool used

- Manual review.
- GalloDaSballo's [research](https://github.com/code-423n4/2023-07-tapioca-findings/issues?q=LidoETHStrategy+buys+stETH+at+1-1+instead+of+buying+it+from+the+Pool+at+Discount+).
- Historical [data on ETH/STETH prices](https://docs.google.com/spreadsheets/d/1iPEuOtCHt39GkeO-R-y1EyFMxKJbNKS-8ze3WqdiVLk/edit#gid=473732970).

## Recommendation

Don't hardcode the method in which STETH is being achieved in Sophon via `_ethTOstEth()` and instead first check the pool and see if it's cheaper to buy stETH directly from it, which would be the case most times.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because users can always optionally call deposit() by pre-converting DAI/sDAI, ETH/stETH, ETH/eTH at their control
