### ISSUE TITLE
Audinarey - `boosterMultiplier` cannot be updated if the `lpSupply` of at least one pool is zero

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#35]
Audinarey

medium

# `boosterMultiplier` cannot be updated if the `lpSupply` of at least one pool is zero

## Summary
In order to set the `_boosterMultiplier` for the farming contract, the `owner` calls `SophonFarming::setBoosterMultiplier(...)`. The `massUpdatePools()` function is compulsorily invoked before updating the `boosterMultiplier` to its new value. 
```solidity
File: SophonFarming.sol
329:     function setBoosterMultiplier(uint256 _boosterMultiplier) public onlyOwner {
322:         if (_boosterMultiplier < 1e18) {
323:             revert InvalidBooster();
324:         }
325:         if (isFarmingEnded()) {
326:             revert FarmingIsEnded();
327:         }
328:         // @audit boosterMultiplier will not be updated if at least one pool is empty
329:   @>    massUpdatePools();
330:         boosterMultiplier = _boosterMultiplier;
331:     }


```
The [`massUpdatePools()` function loops](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L401) over ALL the pools and calls the `updatePool(...)` for each of the pools. However, the `updatePool(...)` function returns and ends execution if it encounters any empty pool without updating the `boosterMultiplier`.
```solidity
File: SophonFarming.sol
411:     function updatePool(uint256 _pid) public {
412:         PoolInfo storage pool = poolInfo[_pid];
413:         if (getBlockNumber() <= pool.lastRewardBlock) {
414:             return;
415:         }
416:         uint256 lpSupply = pool.amount;
417:         uint256 _pointsPerBlock = pointsPerBlock;
418:         uint256 _allocPoint = pool.allocPoint;
419:  @>     if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0) {
420:             pool.lastRewardBlock = getBlockNumber();
421:  @>         return;
422:         }

```

## Vulnerability Detail

- Consider 3 pools lp1, lp2 and lp3 respectively with `lpSupply` 1000lp1, 0lp2, 1000lp3
- admin calls `setBoosterMultiplier(...)`  to change its `boosterMultiplier` from 150 to 200
- as seen on `l419` above, the call to `setBoosterMultiplier(...)` will return and end  because the `lpSupply` of lp2 is zero.
- hence the `boosterMultiplier` is not updated to 200

## Impact
- This breaks core protocol functionality as the `lp` supply of one pool affects core state update of another pool without reverting or notifying the admin
- This can also lead to leak of value for the user or the protocol depending on direction of the update (increasing / decreasing) `boosterMultiplier` value.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L401-L402

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L329-L330

## Tool used

Manual Review

## Recommendation
A trivial solution cannot be suggested for this one as the farming contract currently lacks a proper documentation. However, I will suggest implementing a different `massUpdatePools()` for the setter functions.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because massUpdatePools() will not revert and still update as intended

**Comment by Audinarey** [comment]
Escalate

> invalid because massUpdatePools() will not revert and still update as intended

I disagree with your conclusion

- no mention was made of the `massUpdatePools()` function reverting, instead the `setBoosterMultiplier()` function will complete execution if it encounters a pool with `lpSupply` equal to zero as shown on L421 in the summary section of the report and as such L422 is not executed

```solidity
    function setBoosterMultiplier(uint256 _boosterMultiplier) public onlyOwner {
        if (_boosterMultiplier < 1e18) {
            revert InvalidBooster();
        }
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
  @>      massUpdatePools(); // @audit ends if an empty pool is encountered and next line is not reached
        boosterMultiplier = _boosterMultiplier; 
    }
```

pool `lpSupply` can be empty at different times during a market cycle for instance,
- when it is newly deployed
- at the end of a market cycle when the project becomes less popular

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> > invalid because massUpdatePools() will not revert and still update as intended
> 
> I disagree with your conclusion
> 
> - no mention was made of the `massUpdatePools()` function reverting, instead the `setBoosterMultiplier()` function will complete execution if it encounters a pool with `lpSupply` equal to zero as shown on L421 in the summary section of the report and as such L422 is not executed
> 
> ```solidity
>     function setBoosterMultiplier(uint256 _boosterMultiplier) public onlyOwner {
>         if (_boosterMultiplier < 1e18) {
>             revert InvalidBooster();
>         }
>         if (isFarmingEnded()) {
>             revert FarmingIsEnded();
>         }
>   @>      massUpdatePools(); // @audit ends if an empty pool is encountered and next line is not reached
>         boosterMultiplier = _boosterMultiplier; 
>     }
> ```
> 
> pool `lpSupply` can be empty at different times during a market cycle for instance,
> - when it is newly deployed
> - at the end of a market cycle when the project becomes less popular

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
Please see my commented reasoning on https://github.com/sherlock-audit/2024-05-sophon-judging/issues/226 that is similarly related to this report.

**Comment by Audinarey** [comment]
You are mistaking a `return` for a `continue` statement

This is the case of an early `return` issue that breaks core protocol functionality.
the `return` statement COMPLETES the execution of a function call. 
Quite alright ` pool.lastRewardBlock` will be updated but the call end when the `return` is hit hence L315 is never reached in the scenario described in this finding

For reference, copy the following into remix to understand how `return` works in solidity

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.17;

contract Attacker{
    address public pre;
    uint256 public trim;
    
    constructor () {}

    function changeParam() public {
        
        for (uint8 i = 0; i < 3; i++) {
            if (i == 2) {
                return;
            }
        }
        
        pre = address(type(uint160).max);
        trim = 700;
    }

    function getPre() public view returns(address, uint256) {
        return (pre, trim);
    }
}
``` 

Notice that `pre` and `trim` are never updated as long as the `return` is hit in the loop, 

Therefore as explained in this and other separate findings, immediately one of the pools that is being looped over in `massUpdatePools()` has an `lpSuppy` = 0 is encountered, ` pool.lastRewardBlock` is updated and the call completes, but the `_boosterMultiplier ` is never updated because [this](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L330) line 330 is never reached.

**Comment by Audinarey** [comment]
Hence this finding is valid, because the implementation of the `SophonFarming:: setBoosterMultiplier(...)` function breaks core protocol functionality


I implore you to please read the summary and vulnerability detail sections again.

**Comment by Audinarey** [comment]
@mystery0x I await your response

**Comment by WangSecurity** [comment]
I believe this issue is almost the same as https://github.com/sherlock-audit/2024-05-sophon-judging/issues/226 where we already agreed, that hitting the `return` would only stop the `updatePool` function and `setBoosterMultiplier` would continue its execution.

Planning to reject the escalation and leave the issue as it is, since there is no vulnerability.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Audinarey](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/35/#issuecomment-2144132146): rejected
