### ISSUE TITLE
ironside - Invalid predefined pool can be used in `SophonFarming::depositWeth` function causing potential loss of funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#39]
ironside

medium

# Invalid predefined pool can be used in `SophonFarming::depositWeth` function causing potential loss of funds

## Summary

A user can specify an invalid predefined pool (`sDAI`) when using the `SophonFarming::depositWeth` function, which leads to inconsistent behavior, potential user confusion, and loss of funds. This is because the contract could improperly track the deposited `WETH` as `sDAI`, leading to a situation where the user cannot withdraw their deposited funds correctly.

## Vulnerability Detail

The `SophonFarming::depositWeth` function allows users to deposit `WETH` and convert it to either `wstETH` or `weETH` before depositing it into the specified predefined pool. However, the function does not check if the predefined pool is valid for `WETH` conversions. If a user sets `_predefinedPool` to `sDAI`, the function will still execute without reverting, leading to the contract treating the deposit incorrectly.

## Impact

Users could lose their `WETH`, as the contract does not correctly track the deposit when an invalid pool (`sDAI`) is specified. This could result in users being unable to withdraw their deposited funds.

## Code Snippet

[SophonFarming.sol#L532-L536](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L532-L536)

## Tool used

Manual Review, Foundry

## Proof of code

Place the following test in `SophonFarming.t.sol`:

```javascript
function test_depositWeth_InvalidPool() public {
    // ********** Setup **********
    uint256 amount = 1e18;
    address maliciousUser = makeAddr("malice");

    // Give WETH to account1
    vm.startPrank(deployer);
    weth.deposit{value: amount}();
    weth.transfer(account1, amount);
    vm.stopPrank();

    // Force DAI into contract so it could have enough to convert to sDAI
    dai.mint(maliciousUser, amount);
    vm.prank(maliciousUser);
    dai.transfer(address(sophonFarming), amount);

    // Account1 approves the contract to spend their WETH
    vm.startPrank(account1);
    weth.approve(address(sophonFarming), type(uint256).max);
    vm.stopPrank();
    // ***************************

    // ********** Deposit WETH into an invalid pool (sDAI) **********
    vm.prank(account1);
    // vm.expectRevert("Invalid predefined pool for WETH"); // <--- shouldn't revert before the proposed change is implemented
    sophonFarming.depositWeth(amount, 0, SophonFarmingState.PredefinedPool.sDAI);
}
```

## Recommendation

To prevent this issue, add a validation check to ensure that `_predefinedPool` is either `wstETH` or `weETH` when calling `SophonFarming::depositWeth`. Here is the updated function with the validation:

```diff
function depositWeth(uint256 _amount, uint256 _boostAmount, PredefinedPool _predefinedPool) external {
    IERC20(weth).safeTransferFrom(msg.sender, address(this), _amount);

    uint256 _finalAmount = _wethTOEth(_amount);
    if (_predefinedPool == PredefinedPool.wstETH) {
        _finalAmount = _ethTOstEth(_finalAmount);
    } else if (_predefinedPool == PredefinedPool.weETH) {
        _finalAmount = _ethTOeEth(_finalAmount);
-   }
+   } else {
+      revert("Invalid predefined pool for WETH");
+   }

    _depositPredefinedAsset(_finalAmount, _amount, _boostAmount, _predefinedPool);
}
```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because user input validation to prevent user mistakes is not considered a valid issue. Additionally, the likelihood of the scenario happening is extremely low

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/f0b82fd83a5d85eb8dc7ba2bbce2d49fefb326a4

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
