### ISSUE TITLE
0xboriskataa - Incorrect calculation of `accPointsPerShare` in `updatePool()`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#41]
0xboriskataa

high

# Incorrect calculation of `accPointsPerShare` in `updatePool()`

## Summary
Incorrect calculation of `accPointsPerShare` in `updatePool()`

## Vulnerability Detail
`SophonFarming.sol` uses a lot of the code logic from sushiswap's masterchef contract:
https://github.com/sushiswap/masterchef/blob/master/contracts%2FMasterChef.sol

Both contracts have an `updatePool()` function but there is one key difference and it is in the calculation of the `accSushiPerShare`/`accPointsPerShare` (Sophon uses points instead of ERC-20 tokens). Here is how each one calculates it:

`Masterchef.sol`:
```solidity
pool.accSushiPerShare = pool.accSushiPerShare.add(sushiReward.mul(1e12).div(lpSupply));
```
`SophonFarming.sol`:
```solidity
pool.accPointsPerShare = pointReward / lpSupply + pool.accPointsPerShare;
```
The key difference is that in the Masterchef contract the reward is multiplied by `1e12`. The reason for this is that since `accSushiPerShare` can be a number with decimals and Solidity doesn't handle float numbers, they multiply `sushiReward` by a big number like `1e12` when calculating it and then divide it by the same number when using it.

In `SophonFarming.sol` the multiplication by a big number is missing. However the devision is not and we can see an example of this is in the calculation of the `rewardDebt`:
```solidity
user.rewardDebt = userAmount * pool.accPointsPerShare / 1e18;
```
And here is the calculation of `rewardDebt` in the masterchef contract:
```solidity
user.rewardDebt = user.amount.mul(pool.accSushiPerShare).div(1e12);
```

## Impact
Because of this missing multiplication by a big number the calculation of the points will be incorrect.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L430-L432

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L619-L621

## Tool used

Manual Review

## Recommendation
Multiply `pointReward` by `1e18` before dividing:
```diff
    function updatePool(uint256 _pid) public {
        //...
-        pool.accPointsPerShare = pointReward /
-            lpSupply +
-            pool.accPointsPerShare;

+        pool.accPointsPerShare = pointReward * 1e18 / 
+            lpSupply +
+            pool.accPointsPerShare;

        pool.lastRewardBlock = getBlockNumber();
    }
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because pointReward has been blockMultiplier scaled
