### ISSUE TITLE
ironside - Incorrect upgradeability pattern and storage management can cause state corruption and potential contract bricking

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#44]
ironside

high

# Incorrect upgradeability pattern and storage management can cause state corruption and potential contract bricking

## Summary

The current upgradeability pattern implemented in `Proxy2Step`, `SophonFarming` and `Upgradeable2Step` contracts is flawed due to redundant inheritance and missing initializers. This could lead to incorrect storage management and potential contract failure during upgrades.

## Vulnerability Detail

When implementing upgradeable contracts using a proxy pattern, it is crucial to correctly manage storage and initialization to prevent storage collisions and ensure the correct state is maintained. The following issues have been identified:

- Both `Proxy2Step` and `SophonFarming` inherit from `Upgradeable2Step`, causing shared state variables to be prone to unintended overwrites. If the storage layout changes in the implementation contract without proper initialization and storage management, it can lead to overwritten or corrupted state variables.
- `SophonFarming` and `Upgradeable2Step` do not inherit from `Initializable`, risking the inability to reinitialize the upgraded contract with new variables within the proxy.

## Impact

Without proper initialization and inheritance management, storage slots can be mismanaged. The flawed upgradeability pattern can result in failed upgrades or inconsistent contract state, leading to potential bricking of the contract.

- If the `implementation` variable is overwritten or corrupted during an upgrade, the proxy might lose its reference to the correct `implementation`, rendering the contract inoperable.
- If new state variables in `SophonFarming` and `Upgradeable2Step` are not properly initialized, it can lead to logic errors and potential vulnerabilities in the contract's functionality.

## Code Snippet

- [SophonFarming.sol#L21](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L21)
- [SophonFarming.sol#L108](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L108)
- [Proxy2Step.sol#L6](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/proxies/Proxy2Step.sol#L6)
- [Upgradeable2Step.sol#L14](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/proxies/Upgradeable2Step.sol#L14)

## Tool used

Manual Review

## Recommendation

- Switch to proper initialization mechanism, such as using Openzeppelin's `Initializable`, in both `SophonFarming` and `Upgradeable2Step`, which would allow for future reinitializations, in case new state variables are added.
- Only `SophonFarming` should inherit `Upgradeable2Step` to correctly manage upgradeable state variables, instead of both the `SophonFarming` and `Proxy2Step`. Proxy will set those variables during initialization and reference them during `delegatecall`s to the implementation.
- Add initialization to the `Upgradeable2Step` contract, which would ensure valid storage initialization of its variables in the proxy's storage, as well as switch to using upgradeable version of the `Ownable2Step` contract for the exact same reason.
- The custom proxy contract `Proxy2Step` can be omitted. Instead, use a standardized proxy contract like OpenZeppelin's [TransparentUpgradeableProxy](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/transparent/TransparentUpgradeableProxy.sol) for better security and maintainability.

```diff
-contract Upgradeable2Step is Ownable2Step {
+contract Upgradeable2Step is Initializable, Ownable2StepUpgradeable {
    address public pendingImplementation;
    address public implementation;
    
-   constructor() Ownable(msg.sender) {}

+   function __Upgradeable2Step_init() onlyInitializing {
+       __Ownable2Step_init();
+   }
}
```

```diff
-contract SophonFarming is Upgradeable2Step, SophonFarmingState {
+contract SophonFarming is Initializable, Upgradeable2Step, Ownable2StepUpgradeable {
    function initialize(
        uint256 ethAllocPoint_,
        uint256 sDAIAllocPoint_,
        uint256 _pointsPerBlock,
        uint256 _startBlock,
        uint256 _boosterMultiplier
-   ) public virtual onlyOwner { // <--- onlyOwner is not set before initialization
+   ) public virtual initializer {
+       __Ownable2Step_init();
+       __Upgradeable2Step_init();

        // Initialize state variables
    }
}
```

```diff
// Omit the Proxy2Step.sol altogether
-contract Proxy2Step is Upgradeable2Step{
-    // Code stays the same
-}
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because while the current design is prone to storage collision, the likelihood is slim
