### ISSUE TITLE
T_F_E - Missing Slippage Check

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#45]
T_F_E

medium

# Missing Slippage Check

## Summary
 The `stETH` token is the liquid representation of the ETH staked in lido protocol.

## Vulnerability Detail
There are places in the codebase that indicate that the implementation is assuming a peg of 1 ETH ~= 1 stETH. Even though both tokens have a tendency to keep the peg, this hasn't been always the case as it can be seen in  [this dashboard](https://dune.com/LidoAnalytical/Curve-ETHstETH). There have been many episodes of market volatility that affected the price of stETH, notably the one in last June when stETH traded at ~0.93 ETH.

## Impact
Assuming a fixed peg between `ETH` and `stETH` without accounting for potential deviations can lead to significant financial risks for users. If the `stETH` price drops well below 1 `ETH`, users depositing `ETH` based on the 1: ~1 peg assumption would incur losses, it could also be vulnerable to sandwich attack.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L533
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L808
## Tool used

Manual Review

## Recommendation
Implement Slippage control for users depositing PredefinedPool.wstEth

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because users can always optionally call deposit() by pre-converting DAI/sDAI, ETH/stETH, ETH/eTH at their control
