### ISSUE TITLE
33audits - Incorrect Token Reward Calculation

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#46]
33audits

high

# Incorrect Token Reward Calculation

## Summary
When adding a new pool using the `add()` function the contract does not update the `totalPointsAllocation` by calling `massUpdatePools` unless the a false flag is passed at the bool. This will cause the pool allocation to be incorrect because if a new pool gets added and `pool.allocPoints` isn't updated then for all previous pools then those pools will have a diluted amount of rewards as `totalAllocPoints` will increase.

- https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L153
- https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L195
 
## Vulnerability Detail

Consider the following example.

- Owner of the contracts adds a new pool which is the only pool currently added. Points allocated to this pool will equal 100. In this case the `totalAllocationPoints` for the contract is 100
- 1 block later Alice stakes 10 tokens in the first pool
- 1 week passes and Alice withdraws she receives X amount of tokens
- Bob then goes and deposits 10 tokens into the contract in the first pool
- Owner then goes and adds another pool while passing false for `_withUpdate` with allocation points of 100
- Total allocation points is now 200
- 1 week passes and Bob chooses to withdraw Bob should get the same amount as Alice but will receive X/2 as the first pools allocation points weren't adjusted when the new pool was added but `totalAllocPoints` was.

## Impact

Users rewards will be diluted as new pools are added.

## Code Snippet

This occurs in both the `add` and `set` functions.

```solidity
   function set(uint256 _pid, uint256 _allocPoint, bool _withUpdate) public onlyOwner {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
       //@audit - this will only be called if the bool flag is set to true
        if (_withUpdate) {
            massUpdatePools();
        }

        PoolInfo storage pool = poolInfo[_pid];
        address lpToken = address(pool.lpToken);
        if (lpToken == address(0) || !poolExists[lpToken]) {
            revert PoolDoesNotExist();
        }
        totalAllocPoint = totalAllocPoint - pool.allocPoint + _allocPoint;
        pool.allocPoint = _allocPoint;

        if (getBlockNumber() < pool.lastRewardBlock) {
            pool.lastRewardBlock = startBlock;
        }

        emit Set(lpToken, _pid, _allocPoint);
    }
```
```solidity
function add(uint256 _allocPoint, address _lpToken, string memory _description, bool _withUpdate) public onlyOwner returns (uint256) {
        if (poolExists[_lpToken]) {
            revert PoolExists();
        }
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
       //@audit - this will only be called if the bool flag is set to true
        if (_withUpdate) {
            massUpdatePools();
        }
        uint256 lastRewardBlock =
            getBlockNumber() > startBlock ? getBlockNumber() : startBlock;
        totalAllocPoint = totalAllocPoint + _allocPoint;
        poolExists[_lpToken] = true;

        uint256 pid = poolInfo.length;

        poolInfo.push(
            PoolInfo({
                lpToken: IERC20(_lpToken),
                l2Farm: address(0),
                amount: 0,
                boostAmount: 0,
                depositAmount: 0,
                allocPoint: _allocPoint,
                lastRewardBlock: lastRewardBlock,
                accPointsPerShare: 0,
                description: _description
            })
        );
```

## Tool used

Manual Review

## Recommendation
Remove the `_withUpdate` parameter and instead call `massUpdatePools()` anytime a new pool is added or the allocation points are updated via the `set()` function. This should always be called and should not be dependent on a parameter flag.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/6d117397d57a39a865cee0621cabf9154fb6fd71

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
