### ISSUE TITLE
araj - Precision Loss for `_boostAmount` in `SophonFarming::_deposit()`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#48]
araj

medium

# Precision Loss for `_boostAmount` in `SophonFarming::_deposit()`

## Summary
There is precision loss for `_boostAmount` in `SophonFarming::_deposit()` due to the priority of division over multiplication.

## Vulnerability Detail
Solidity rounds down the result of an integer division, and because of that, it is always recommended to multiply before
dividing to avoid that precision loss. In the case of a prior division over multiplication, the final result may face serious precision loss

In `SophonFarming::_deposit()`,  `boostAmount` is taken as input and multiplied with `boosterMultiplier` and divide by 1e18
```solidity
 _boostAmount = _boostAmount * boosterMultiplier / 1e18;
```
Now the problem is,  `_boostAmount` is already multiplied and divided in `SophonFarming::_depositPredefinedAsset()` before sending to `_deposit()`
```solidity
   _boostAmount = _boostAmount * _finalAmount / _initalAmount;
```

## Impact
A lack of precision exists in _boostAmount in _deposit() function

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L563C6-L563C68
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L608

## Tool used
Manual Review

## Recommendation
Combine both equations together in _deposit()
```diff
-  _boostAmount = _boostAmount * boosterMultiplier / 1e18;
-    _boostAmount = _boostAmount * _finalAmount / _initalAmount;
+ _boostAmount = (_boostAmount * _finalAmount * boosterMultiplier) / _initalAmount / 1e18;
```

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the arithmetic operations involved stem from two different functions
