### ISSUE TITLE
fyamf - Wrong calculation of settled reward

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#50]
fyamf

high

# Wrong calculation of settled reward

## Summary
Due to the rounding issue, the reward settled to an user is calculated incorrectly. 

## Vulnerability Detail

The procedure to calculate the settled reward of an user during depositing is as follows:
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L590-L595

Where the `pool.accPointsPerShare` is calculated during updating the pool:

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L423-L432

In summary, the settled reward is calculated in some steps as follows. This procedure is done during both depositing, withdrawing, and increasing boost.
```solidity
// step 1
uint256 pointReward =
            blockMultiplier *
            _pointsPerBlock *
            _allocPoint /
            totalAllocPoint;

// step 2
pool.accPointsPerShare = pointReward /
            lpSupply +
            pool.accPointsPerShare;

// step 3
user.rewardSettled =
            userAmount *
            pool.accPointsPerShare /
            1e18 +
            user.rewardSettled -
            user.rewardDebt;
```
In step 2, `pool.accPointsPerShare` is rounded down because of the division of `pointReward ` over `lpSupply`. So, the resulted `pool.accPointsPerShare` is less than the expected value, and it will reduce the settled reward of the user.

By looking at the way the pending points is calculated, it will be clear where the problem is.

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L357-L384

The pending points here is calculated in the following steps:
```solidity
// step 1
uint256 pointReward =
                blockMultiplier *
                pointsPerBlock *
                pool.allocPoint /
                totalAllocPoint;

// step 2
 accPointsPerShare = pointReward *
                1e18 /
                lpSupply +
                accPointsPerShare;

// step 3
return user.amount *
            accPointsPerShare /
            1e36 +
            user.rewardSettled -
            user.rewardDebt;
```

As it shows, step 2 is multiplied by `1e18`, while step 2 in calculating settled reward misses it. Moreover, at step 3, it is divided by `1e36`,  while in step 2 in calculating settled reward it is divided by `1e18`.

By adding the following test to `SophonFarming.t.sol`, the result shows the issue. Please note that I have added a helper function to `SophonFarming.sol` to get the settled reward of the user more easily. The values are chosen to show the issue clearly.

```solidity
function test_RoundingIssue() public {
        // set the pointsPerBlock to 25
        vm.startPrank(deployer);
        sophonFarming.setPointsPerBlock(25);

        uint amountToDeposit = 250e18;
        vm.deal(account1, amountToDeposit);
        vm.startPrank(account1);

        uint256 wsthDepositedAmount = WstETHRate(StETHRate(amountToDeposit));
        uint256 poolId = sophonFarming.typeToId(
            SophonFarmingState.PredefinedPool.wstETH
        );

        sophonFarming.depositEth{value: amountToDeposit}(
            0,
            SophonFarmingState.PredefinedPool.wstETH
        );
        assertEq(address(account1).balance, 0);

        // 30 blocks is passed
        vm.roll(block.number + 30);

        console.log("deposited amount of wstETH: ", wsthDepositedAmount);
        console.log(
            "the pending reward of the user",
            sophonFarming.pendingPoints(poolId, account1)
        );

        // withdrawing a small amount just to update the user's data
        sophonFarming.withdraw(poolId, 1);

        console.log(
            "the reward settled to the user: ",
            sophonFarming.getSettledReward(account1, poolId)
        );
    }
```

Helper function:
```solidity
function getSettledReward(
        address _user,
        uint256 _pid
    ) external view returns (uint256) {
        UserInfo memory uinfo = userInfo[_pid][_user];
        return uinfo.rewardSettled;
    }
```

The result:
```Java
deposited amount of wstETH:  215083179283308346188
the pending reward of the user 249
the reward settled to the user:  215
```

It shows that the expected reward is `249`, while only `215` is settled to the user.  Simply the total to-be-distributed reward during this 30 blocks is `30 * 25 * 20000 / 60000 = 250`, where `20000` and `60000` are allocation point of the pool and total allocation point, respectively. So, due to this issue the pending reward is the correct value, while the settled reward is calculated wrongly.

## Impact
 - Wrong calculation of rewards.
 - Different result between the pending points calculation and settled reward.

## Tool used

Manual Review

## Recommendation
Change the settled reward calculation as follows, in all functions `_depoist`, `withdraw`, and `increaseBoost`.
```solidity
function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
       //....
       user.rewardSettled =
           userAmount *
           pool.accPointsPerShare /
           1e36 +
           user.rewardSettled -
           user.rewardDebt;
       //.....
}
```
```solidity
function withdraw(uint256 _pid, uint256 _withdrawAmount) external {
       //....
       user.rewardSettled =
           userAmount *
           pool.accPointsPerShare /
           1e36 +
           user.rewardSettled -
           user.rewardDebt;
       //.....
}
```
```solidity
function increaseBoost(uint256 _pid, uint256 _boostAmount) external {
       //....
       user.rewardSettled =
           userAmount *
           pool.accPointsPerShare /
           1e36 +
           user.rewardSettled -
           user.rewardDebt;
       //.....
}
```
```solidity
function updatePool(uint256 _pid) public {
        //......

        pool.accPointsPerShare = pointReward * 1e18 /
            lpSupply +
            pool.accPointsPerShare * 1e18;

        //.....
}
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because getPendingPoints() will not practically be used till point farming has ended. The higher precision adopted is by design
