### ISSUE TITLE
0xNoodle - Inconsistent Block Number Handling

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#54]
0xNoodle

medium

# Inconsistent Block Number Handling

## Summary
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L876

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L434

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L420

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L364

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L232

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L211

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L164

The getBlockNumber() function in the SophonFarming contract relies on block.number, which can lead to inconsistencies across different Layer 2 (L2) solutions like Optimism and Arbitrum. This discrepancy can cause timing issues, especially when the contract is deployed on multiple chains.

## Vulnerability Detail

On Optimism, block.number returns the L2 block number, while on Arbitrum, it returns the L1 block number. This discrepancy can lead to different timing behaviors on different chains, affecting contract logic and time-sensitive operations.

## Impact

Using block.number can result in different timing behaviors on different chains, leading to potential issues in contract logic, especially for time-sensitive operations like farming periods, reward calculations, and voting.

Contracts relying on block.number may behave unpredictably when deployed on multiple L2 solutions, affecting functionalities and user experience.

## Code Snippet

```sol
function getBlockNumber() virtual public view returns (uint256) {
        return block.number;
    }
```

## Tool used

Manual Review

## Recommendation

Implement a clock mechanism to track time consistently across different chains. This can be done using timestamps (block.timestamp) or a custom clock contract.

 For Arbitrum, use ArbSys(address(100)).arbBlockNumber() to get the L2 block number. Implement chain-specific logic to handle different L2 solutions.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the smart contracts are going to be deployed on Ethereum for this audit
