### ISSUE TITLE
0xNoodle - Insufficient Validation in setL2FarmForPool() Function of SophonFarming Contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#56]
0xNoodle

medium

# Insufficient Validation in setL2FarmForPool() Function of SophonFarming Contract

## Summary

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L264

The setL2FarmForPool() function in the SophonFarming contract lacks essential validations and does not follow the check-effects-interactions (CEI) pattern. These omissions can lead to misconfigurations and potential vulnerabilities.

## Vulnerability Detail

The function does not validate that the _l2Farm address is not address(0), does not ensure the address is a contract, does not check if the pool with _pid exists, and does not follow the CEI pattern. This can lead to setting an invalid or malicious L2 farm address, resulting in potential misconfigurations and security risks.

## Impact

Without checking the existence of the pool, the function can attempt to update a non-existent pool, leading to runtime errors.

Setting the L2 farm to address(0) can lead to unintended behavior and contract malfunction.

Setting the L2 farm to a non-contract address can cause the contract to fail when interacting with the L2 farm.

## Code Snippet
```sol
function setL2FarmForPool(uint256 _pid, address _l2Farm) public onlyOwner {
        poolInfo[_pid].l2Farm = _l2Farm;
    }

```

## Tool used

Manual Review

## Recommendation
Ensure the _l2Farm address is not address(0), Validate that the pool with the given _pid exists. Adhere to the check-effects-interactions pattern for consistency and security best practices.

To ensure that the pool with the given _pid exists
```sol

function setL2FarmForPool(uint256 _pid, address _l2Farm) public onlyOwner {
    // Check that the pool with the given _pid exists
    require(_pid < poolInfo.length, "Pool does not exist");
   
 require(address(poolInfo[_pid].lpToken) != address(0), "Invalid pool");

    // Ensure the _l2Farm address is not zero
    require(_l2Farm != address(0), "Invalid L2 farm address");

    // Existing logic...
    poolInfo[_pid].l2Farm = _l2Farm;
}
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because of zero address input validation
