### ISSUE TITLE
SovaSlava - Hardcoded gas limit to external call

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#60]
SovaSlava

medium

# Hardcoded gas limit to external call

## Summary
Hardcoded gas limil value in cal to other contract could be incorrect in the future, when price for some opcodes will increase. And all calls will revert.

Sponsor said in discord channel, that bridge is out of scope, but this issue not about bridge, its about this contract, which make call to external contract.
## Vulnerability Detail
Over time, the price of opcodes may increase (this has happened before) and gas restrictions may become an obstacle to making a call to another contract. the transaction will be reverted.
## Impact
All transactions to bridge could be reverted.
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L766-L770
## Tool used

Manual Review

## Recommendation
Allow variable, which will keep value for gaslimit and owner should have control and function to change this value, if it needed

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because bridge logic not implemented and not covered by this audit
