### ISSUE TITLE
EgisSecurity - Loss of funds when deposit flow uses `_ethTOeEth`, because deposit amount is not handled correctly

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#64]
EgisSecurity

high

# Loss of funds when deposit flow uses `_ethTOeEth`, because deposit amount is not handled correctly

## Summary

`SophonFarming` contract has a few lp pools, which are interest bearing such as `stEth`, `eEth`, etc. This is smart to be used in such system, where funds are being locked, but also do generate some yield. However, developers should be very careful integrating such tokens, because the complexity may increase as they are using shares to calculate and track corresponding balance of the underlying token (eth for example).

We will concentrate in the following flow of the system:
 `depositWeth(PredefinedPool.weETH`) \
                                                                 | ---> `_ethTOeEth` -> `_eethTOweEth` -> `_deposit` 
     `depositEth(PredefinedPool.weETH`/

and why the accounting is not handled correct, which result is using lower amount for the virtual balance tracked by the contract.
## Vulnerability Detail

Lets suppose we want to use eth and stake in `weETH` pool.
1. We call [depositEth](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L503) with `msg.valueof = 1 eth` and `_predefinedPool = PredefinedPool.weETH`  (we will exclude `boostAmount` for this example, becase it is not important)
2. We enter [_ethTOeEth](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L832-L835), which calls `eETHLiquidityPool::deposit` function and here is the root of the problem. 
The code assumes that `deposit` operation return the exact amount of `eETH`, but instead it returns the shares. You can check that [here](https://etherscan.deth.net/address/0x308861A430be4cce5502d0A12724771Fc6DaF216)
```solidity
    function _deposit(address _recipient, uint256 _amountInLp, uint256 _amountOutOfLp) internal returns (uint256) {
        totalValueInLp += uint128(_amountInLp);
        totalValueOutOfLp += uint128(_amountOutOfLp);
        uint256 amount = _amountInLp + _amountOutOfLp;
        uint256 share = _sharesForDepositAmount(amount);
        if (amount > type(uint128).max || amount == 0 || share == 0) revert InvalidAmount();

        eETH.mintShares(_recipient, share);

        return share;
    }
```
3. In times of writing this report (05.2024) depositing 1 eth will mint user `962402708637095211` (0.96 ether) `eETH` shares to the user
4. `_ethTOeEth` return the value of the minted shares assuming it is the amount of `eETH` tokens (using 0.96 ether, instead of 1 ether = instant lock of 0.04 ether)
5.  Flow continues  and we enter [_depositPredefinedAsset](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L548) with the `_amount = shares`, instead of real amount.
6. 6. Then we enter [_eethTOweEth](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L843-L846) and call `weETH(weETH).wrap(_amount)`, which expect the raw `eETH` amount and we can check that [here](https://etherscan.deth.net/address/0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee):
```solidity
    function wrap(uint256 _eETHAmount) public returns (uint256) {
        require(_eETHAmount > 0, "weETH: can't wrap zero eETH");
        uint256 weEthAmount = liquidityPool.sharesForAmount(_eETHAmount);
        _mint(msg.sender, weEthAmount);
        eETH.transferFrom(msg.sender, address(this), _eETHAmount);
        return weEthAmount;
    }
```
- `eETH.transferFrom` converts `_eETHAmount` to shares, which calculation in 0.92 ether instead of 0.96 ether:
```solidity
    function _transfer(address _sender, address _recipient, uint256 _amount) internal {
        uint256 _sharesToTransfer = liquidityPool.sharesForAmount(_amount);
        _transferShares(_sender, _recipient, _sharesToTransfer);
        emit Transfer(_sender, _recipient, _amount);
    }
```
- As a result we receive `926218973592017577` `weEth`, instead of `962402708637095211` (loss of 0.04, or $150 in time of writing this 1 ETH = $3 850)
7. Then the flow continues using newly calculated amount `_finalAmount` as `amount` argument for [_deposit](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L565) function
8. This result in:
- Funds loss for depositor, because his balance is incremented with amount, which is $150 less than the original deposited
- Those funds are locked in the contract
## Impact
- Lost of funds for depositors.
## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L834
## Tool used

Manual Review

## Recommendation
Inside `_ethTOeEth` call `IeETHLiquidityPool::amountForShare`  for the amount returned from `IeETHLiquidityPool(eETHLiquidityPool).deposit{value: _amount}(address(this));`
```diff
    function _ethTOeEth(uint256 _amount) internal returns (uint256) {
        // deposit returns exact amount of eETH
+         uint256 shares =  IeETHLiquidityPool(eETHLiquidityPool).deposit{value: _amount}(address(this));
+         return IeETHLiquidityPool(eETHLiquidityPool).amountForShare(shares);
-        return IeETHLiquidityPool(eETHLiquidityPool).deposit{value: _amount}(address(this));
    }
```
Duplicate of https://github.com/sherlock-audit/2024-05-sophon-judging/issues/4

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because users can always optionally call deposit() by pre-converting DAI/sDAI, ETH/stETH, ETH/eTH at their control

**Comment by mystery0x** [comment]
This report is valid and could have been deduped under #4.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/73adb6759b899e1a192fb5e28a5cd6202b5c3ff2

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
