### ISSUE TITLE
air_0x - weETH  and wstETH reuse  ethAllocPoint_ parameter  in the initialize() function   will lead to unfair or incorrect reward distribution if different alloc points are to be used

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#68]
air_0x

medium

# weETH  and wstETH reuse  ethAllocPoint_ parameter  in the initialize() function   will lead to unfair or incorrect reward distribution if different alloc points are to be used

## Summary
The  `initialize()` function reuses points `ethAllocPoint_` parameter  for the approval of both `wstETH` and `weETH`  which will  lead to unfair or incorrect reward distribution if different alloc points are to be used.

## Vulnerability Detail
Below is the initialize function :
```solidity
 function initialize(uint256 ethAllocPoint_, uint256 sDAIAllocPoint_, uint256 _pointsPerBlock, uint256 _startBlock, uint256 _boosterMultiplier) public virtual onlyOwner {
        if (_initialized) {
            revert AlreadyInitialized();
        }

        pointsPerBlock = _pointsPerBlock;

        if (_startBlock == 0) {
            revert InvalidStartBlock();
        }
        startBlock = _startBlock;

        if (_boosterMultiplier < 1e18) {
            revert InvalidBooster();
        }
        boosterMultiplier = _boosterMultiplier;

        poolExists[dai] = true;
        poolExists[weth] = true;
        poolExists[stETH] = true;
        poolExists[eETH] = true;

        // sDAI
        typeToId[PredefinedPool.sDAI] = add(sDAIAllocPoint_, sDAI, "sDAI", false);
        IERC20(dai).approve(sDAI, 2**256-1);
//@audit 
        // wstETH
        typeToId[PredefinedPool.wstETH] = add(ethAllocPoint_, wstETH, "wstETH", false);
        IERC20(stETH).approve(wstETH, 2**256-1);
//@audit
        // weETH
        typeToId[PredefinedPool.weETH] = add(ethAllocPoint_, weETH, "weETH", false);
        IERC20(eETH).approve(weETH, 2**256-1);

        _initialized = true;
    }
```
As you can see, the `wstETH` and `weETH` share the same `ethAllocPoint_` parameter  added to the SophonFarming contract.

In the  `SophonFarming.t.sol` test function `setUp()`  below , we  can  also see that the parameters given for the initialize() function are wstETHAllocPoint, sDAIAllocPoint, pointsPerBlock, startBlock and boosterMultiplier excluding ethAllocPoint which is present as `ethAllocPoint_`  parameter in the `initialize()`  function  

```solidity
//@audit : wstETHAllocPoint is present but not ethAllocPoint
sophonFarming.initialize(wstETHAllocPoint, sDAIAllocPoint, pointsPerBlock, startBlock, boosterMultiplier);
```

## Impact
Both `wstETH` and `weETH` would receive rewards based on the same allocation point, leading to unfair or incorrect reward distribution

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L108

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/test/SophonFarming.t.sol#L151

## Tool used

Manual Review

## Recommendation

Ensure that each pool uses a unique allocation point parameter.

```solidty
 //@TODO : add wstETHAllocPoint_ as wstEth alloc point parameter
     

    function initialize( uint256 ethAllocPoint_, uint256 wstETHAllocPoint_, uint256 sDAIAllocPoint_, uint256 _pointsPerBlock, uint256 _startBlock, uint256 _boosterMultiplier) public virtual onlyOwner {
        if (_initialized) {
            revert AlreadyInitialized();
        }

        pointsPerBlock = _pointsPerBlock;

        if (_startBlock == 0) {
            revert InvalidStartBlock();
        }
        startBlock = _startBlock;

        if (_boosterMultiplier < 1e18) {
            revert InvalidBooster();
        }
        boosterMultiplier = _boosterMultiplier;

        poolExists[dai] = true;
        poolExists[weth] = true;
        poolExists[stETH] = true;
        poolExists[eETH] = true;

        // sDAI
        typeToId[PredefinedPool.sDAI] = add(sDAIAllocPoint_, sDAI, "sDAI", false);
        IERC20(dai).approve(sDAI, 2**256-1);

       //@audit 
       //TODO: change alloc point paramter  from ethAllocPoint_  to wstETHAllocPoint_
        // wstETH
        typeToId[PredefinedPool.wstETH] = add(wstETHAllocPoint_, wstETH, "wstETH", false);
        IERC20(stETH).approve(wstETH, 2**256-1);


        // weETH
        typeToId[PredefinedPool.weETH] = add(ethAllocPoint_, weETH, "weETH", false);
        IERC20(eETH).approve(weETH, 2**256-1);

        _initialized = true;
    }
```
If the intended goal is to share the same alloc point for both  `wstETH` and `weETH` then rename the alloc point paramter name  from  `wstETHAllocPoint` to `ethAllocPoint` in the `SophonFarming.t.sol` test contract to match.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because set() can always be used to updates a given pool's allocation point if need be
