### ISSUE TITLE
BiasedMerc - Tokens converted on deposit are not converted back, which can cause users to be unable to utilise withdrawn funds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#7]
BiasedMerc

medium

# Tokens converted on deposit are not converted back, which can cause users to be unable to utilise withdrawn funds

## Summary

When users (which may be EOAs or Contracts) utilise `SophonFarming.sol` to farm rewards from LST and earn point from Sophon additionally, they can choose multiple currencies to utilise. These currencies that are deposited are converted to LST tokens and stored within `SophonFarming.sol` and are withdrawable. 

However the converted tokens are not swapped back to the tokens that were deposited, and there is no functionality within the protocol to achieve this. This can cause issues as many contracts may utilise a set number of ERC20 tokens and if during withdraw they receive an unsupported token, they will be unable to withdraw. This is especially important for the `ETH` deposit, as that directly utilises Native Ether, therefore the user (a contract in this case) may not even support ERC20 tokens.

## Vulnerability Detail
[SophonFarming.sol#L503-L566](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L503-L566)
```solidity
    function depositEth(uint256 _boostAmount, PredefinedPool _predefinedPool) public payable {
        if (msg.value == 0) {
            revert NoEthSent();
        }

        uint256 _finalAmount = msg.value;
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
        }

        _depositPredefinedAsset(_finalAmount, msg.value, _boostAmount, _predefinedPool);
    }
...SKIP!...
    function depositWeth(uint256 _amount, uint256 _boostAmount, PredefinedPool _predefinedPool) external {
        IERC20(weth).safeTransferFrom(
            msg.sender,
            address(this),
            _amount
        );

        uint256 _finalAmount = _wethTOEth(_amount);
        if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _ethTOstEth(_finalAmount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _ethTOeEth(_finalAmount);
        }

        _depositPredefinedAsset(_finalAmount, _amount, _boostAmount, _predefinedPool);
    }
...SKIP!...
    function _depositPredefinedAsset(uint256 _amount, uint256 _initalAmount, uint256 _boostAmount, PredefinedPool _predefinedPool) internal {

        uint256 _finalAmount;

        if (_predefinedPool == PredefinedPool.sDAI) {
            _finalAmount = _daiTOsDai(_amount);
        } else if (_predefinedPool == PredefinedPool.wstETH) {
            _finalAmount = _stEthTOwstEth(_amount);
        } else if (_predefinedPool == PredefinedPool.weETH) {
            _finalAmount = _eethTOweEth(_amount);
        } else {
            revert InvalidDeposit();
        }
```
Users can deposit once currency that will then be converted into a LST to earn rewards. 
[SophonFarming::withdraw()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L699-L742)
```solidity
    function withdraw(uint256 _pid, uint256 _withdrawAmount) external {
        if (isWithdrawPeriodEnded()) {
            revert WithdrawNotAllowed();
        }
        if (_withdrawAmount == 0) {
            revert WithdrawIsZero();
        }

        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
        updatePool(_pid);

        uint256 userDepositAmount = user.depositAmount; // Non-boost amount

        if (_withdrawAmount == type(uint256).max) {
            _withdrawAmount = userDepositAmount;
        } else if (_withdrawAmount > userDepositAmount) {
            revert WithdrawTooHigh(userDepositAmount);
        }

        uint256 userAmount = user.amount;
        user.rewardSettled =
            userAmount *
            pool.accPointsPerShare /
            1e18 +
            user.rewardSettled -
            user.rewardDebt;

        user.depositAmount = userDepositAmount - _withdrawAmount;
        pool.depositAmount = pool.depositAmount - _withdrawAmount;

        userAmount = userAmount - _withdrawAmount;

        user.amount = userAmount;
        pool.amount = pool.amount - _withdrawAmount;

>>      pool.lpToken.safeTransfer(msg.sender, _withdrawAmount);

        user.rewardDebt = userAmount *
            pool.accPointsPerShare /
            1e18;

        emit Withdraw(msg.sender, _pid, _withdrawAmount);
    }
```
When withdrawing the tokens are not converted back to the tokens that were deposited, this can cause issues.

## Impact

If a contract that utilises native ETH to stake in `SophonFarming.sol` utilising the Native ETH functionality:
```solidity
    receive() external payable {
        if (msg.sender == weth) {
            return;
        }

        depositEth(0, PredefinedPool.wstETH);
    }
```
then it should also withdraw in Native ETH, or have an option to do so. If a contract deposits Native ETH into `SophonFarming.sol` they will be unable to use any withdrawns funds as they will not be converted back to Native ETH, causing the user to have stuck funds in certain cases.

## Code Snippet

[SophonFarming.sol#L503-L566](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L503-L566)
[SophonFarming::withdraw()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L699-L742)

## Tool used

Manual Review

## Recommendation

It is important to ensure that users deposit and withdraw the same tokens (or have the option to), to ensure that they are able to transfer and utilise the tokens in question. Ensure that that is a function that reconverts the funds back into the same token (ERC20 or Native ETH) that was used during deposit.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because that's the intended design where users decide when and how to get back ETH with least slippage
