### ISSUE TITLE
Audinarey - users who make deposit into a pool with zero/empty `pool.amount` (`lpSupply`) will loose their asset and not earn points

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#70]
Audinarey

high

# users who make deposit into a pool with zero/empty `pool.amount` (`lpSupply`) will loose their asset and not earn points

## Summary
Whenever a user makes a deposit into a empty pool, their asset is completely lost because their `UserInfo` is not recorded also the pool's `PoolInfo` are not updated before the `_deposit(...)` call ends.

The problem arises due to the improper implementation of the `updatePool(...)` function which I correct in the Recommendation section of this report.

## Vulnerability Detail

When a user deposits any asset, an internal call is made to `_deposit(...)` function to update the state variables for the pool and the users details in the pool.

The `_deposit(...)` function **_compulsorily_** calls `updatePool(...)` function to settle the pool's accounting before the new deposit is recorded. However, the update function returns and ends execution when the pool's `lpSupply` is zero as shown below on L421
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L411-L422

Hence the user made a deposit but has no record for points or lp in storage of the `SophonFarming` contract.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L574-L587

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L411-L422

## Tool used

Manual Review

## Recommendation
Modify the deposit function as shown below

```solidity
    function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_depositAmount == 0) {
            revert InvalidDeposit();
        }
        if (_boostAmount > _depositAmount) {
            revert BoostTooHigh(_depositAmount);
        }


        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
 +      if (pool.amount > 0) {
 +           updatePool(_pid);
 +     }

```

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because that's the intended design for the first depositor

**Comment by Audinarey** [comment]
Escalate


> invalid because that's the intended design for the first depositor

This finding does not mention the anything about first depositor. It is referring to the early termination owing to the `return` statement in the `updatePool(...)` function which ends execution whenever the the `lpSupply` of the pool is 0 as show below.
```solidity
    function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_depositAmount == 0) {
            revert InvalidDeposit();
        }
        if (_boostAmount > _depositAmount) {
            revert BoostTooHigh(_depositAmount);
        }

        PoolInfo storage pool = poolInfo[_pid];
        UserInfo storage user = userInfo[_pid][msg.sender];
        updatePool(_pid);

        uint256 userAmount = user.amount;
        user.rewardSettled =
            userAmount *
            pool.accPointsPerShare /
            1e18 +
            user.rewardSettled -
            user.rewardDebt;

        // booster purchase proceeds
        heldProceeds[_pid] = heldProceeds[_pid] + _boostAmount;

        // deposit amount is reduced by amount of the deposit to boost
        _depositAmount = _depositAmount - _boostAmount;
```

As a matter of fact, the pool can be empty at different times of the market cycle e.g when a project becomes less popular at the end of a market cycle.


I really don't understand what you mean by first depositor.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> 
> > invalid because that's the intended design for the first depositor
> 
> This finding does not mention the anything about first depositor. It is referring to the early termination owing to the `return` statement in the `updatePool(...)` function which ends execution whenever the the `lpSupply` of the pool is 0 as show below.
> ```solidity
>     function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
>         if (isFarmingEnded()) {
>             revert FarmingIsEnded();
>         }
>         if (_depositAmount == 0) {
>             revert InvalidDeposit();
>         }
>         if (_boostAmount > _depositAmount) {
>             revert BoostTooHigh(_depositAmount);
>         }
> 
>         PoolInfo storage pool = poolInfo[_pid];
>         UserInfo storage user = userInfo[_pid][msg.sender];
>         updatePool(_pid);
> 
>         uint256 userAmount = user.amount;
>         user.rewardSettled =
>             userAmount *
>             pool.accPointsPerShare /
>             1e18 +
>             user.rewardSettled -
>             user.rewardDebt;
> 
>         // booster purchase proceeds
>         heldProceeds[_pid] = heldProceeds[_pid] + _boostAmount;
> 
>         // deposit amount is reduced by amount of the deposit to boost
>         _depositAmount = _depositAmount - _boostAmount;
> ```
> 
> As a matter of fact, the pool can be empty at different times of the market cycle e.g when a project becomes less popular at the end of a market cycle.
> 
> 
> I really don't understand what you mean by first depositor.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
This scenario happens when the first depositor for the pool deposits only after `getBlockNumber() > pool.lastRewardBlock`, i.e. after the very first block where point farming could have begun had deposit been made beforehand. Because `updatePool()` is called before `user.amount` is updated, `lpSupply == 0`; hence `pool.lastRewardBlock` will have to be checked point with `getBlockNumber()`, i.e. the very first block where point farming could begin is now pushed back.

**Comment by WangSecurity** [comment]
I believe the problem that Watson highlights is the same as #226: the `return` in `updatePool` completes the execution of the deposit. In the same #226 we've agreed that it only finishes the execution of the `updatePool`, hence, the `deposit` function will continue its execution after hitting `return` in the `updatePool`.

Therefore, I believe the code works correctly and as expected. Planning to reject te escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Audinarey](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/70/#issuecomment-2144677605): rejected
