### ISSUE TITLE
yamato - `add` and `set` should always update all pools

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#71]
yamato

medium

# `add` and `set` should always update all pools

## Summary
if pools are not updated prior to `add`/`set`, accounting will be broken 

## Vulnerability Detail
When calling `add`/`set`, this changes the `totalAlloc` and the pool's relative allocation one with another.
If upon such call, pools are not updated, it would cause discrepancies.

Let's say if there have been only 2 pools with equal allocation which have not been updated for X time and then a third pool is added with same allocation, if pools are not updated before the `add`, rewards will be calculated as if the 2 pools have had 33% of total allocation throughout the whole time X.

## Impact
Incorrect rewards calculation

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L161

## Tool used

Manual Review

## Recommendation
Always update all pools

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean
