### ISSUE TITLE
0xsi - Allowing Setting startBlock to a Past Block in `SophonFarming::setStartBlock` Enables Premature Farming Start

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#73]
0xsi

medium

# Allowing Setting startBlock to a Past Block in `SophonFarming::setStartBlock` Enables Premature Farming Start

## Summary
The function `SophonFarming::setStartBlock` does not prevent the `startBlock` from being set to a past block, which could result in logical inconsistencies or unintended behavior. This could potentially disrupt the intended functionality of time-based operations in the contract.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L272-L280

## Impact

The owner of the contract could maliciously set the `startBlock` to a past block.

## Vulnerability Detail

This could cause the farming process (or any time-dependent mechanism) to start immediately or at an unintended time, bypassing the actual intended start logic. For example, if rewards are distributed based on block numbers, setting the `startBlock` in the past could manipulate the reward distribution process.

## Tool used

Manual Review

## Recommendation

```diff
+        if (getBlockNumber() > _startBlock) {
+            revert InvalidStartBlock();
+        }

```

**Comment by sherlock-admin2** [comment]
2 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the suggested mitigation is already well in place. It's pool.lastRewardBlock not getting updated for syncing that matters 

**0xreadyplayer1** commented:
>  The startBlock can be set in the past or future only if the farming is not started which is intended behavior also As Owner is Trusted - the statement by watson `The owner of the contract could maliciously set the `startBlock` to a past block.` deems this issue lie in Out of scope.
