### ISSUE TITLE
utsav - User can `deposit` assets before farming started ie `startBlock`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#78]
utsav

high

# User can `deposit` assets before farming started ie `startBlock`

## Summary
User can `deposit` assets before farming started ie `startBlock` as there is no checks  which will lead to immediate `rewardSettled`

## Vulnerability Detail
Assets are `deposited` in the protocol through all the deposits functions. Also there is `no check` if the farming is started or not.
```solidity
function _deposit(uint256 _pid, uint256 _depositAmount, uint256 _boostAmount) internal {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_depositAmount == 0) {
            revert InvalidDeposit();
        }
        if (_boostAmount > _depositAmount) {
            revert BoostTooHigh(_depositAmount);
        }
      .....
    }
```
A malicious actor can deposit before `startBlock` and will immediately have `rewardSettled` when farming is started

## Impact
Malicious actor can game the `rewardSettled`

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L574C5-L625C1
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L411C5-L436C1

## Tool used
Manual Review  + VS Code

## Recommendation
`Don't` allow depositing assets `before` farming started

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because of intended design. Users might want to standby and maximize point farming from the very beginning
