### ISSUE TITLE
aslanbek - Non-boosting deposits that were not withdrawn before `endBlockForWithdrawals` are stuck in `SophonFarming` proxy

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#8]
aslanbek

medium

# Non-boosting deposits that were not withdrawn before `endBlockForWithdrawals` are stuck in `SophonFarming` proxy

## Vulnerability Detail

`SophonFarming` allows users to deposit an arbitrary amount of whitelisted tokens and choose how much they want to use for boosting. All deposits that were not used for boosting can be `withdrawn` by the staker. Function `withdraw` has `isWithdrawPeriodEnded` check, that does not allow withdrawals after `endBlockForWithdrawals`. The problem is that the owner can never withdraw non-boosting deposits, and stakers can do so only before `endBlockForWithdrawals`. So once withdraw period is over, nobody can withdraw non-boosting deposits from the contract.

## Impact

Stuck deposits in the contract, which can be retrieved only by upgrading the proxy.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L21

## Tool used

Manual Review

## Recommendation

Add a privileged function to rescue all tokens held by the contract after `endBlockForWithdrawals`, or allow stakers to withdraw their deposit at any time.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because admin can always set endBlock to zero to temporarily allow indefinite period of withdrawal. Otherwise there should be a resolution when pool.depositAmount is bridged
