### ISSUE TITLE
Tricko - If stETH:ETH and eETH:ETH exchange ratios exceed 1 users may lose funds during deposits.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#81]
Tricko

medium

# If stETH:ETH and eETH:ETH exchange ratios exceed 1 users may lose funds during deposits.

## Summary
During deposits, there is no minimum limit on the `_finalAmount` after token conversions. Because of this, when the stETH:ETH and eETH:ETH exchange ratios exceed 1, such as during periods of high market volatility, users may lose funds during these conversions.

## Vulnerability Detail
According to the codebase and the test suite, eight tokens can be deposited (DAI, sDAI, ETH, WETH, stETH, wstETH, eETH, and weETH). However, only three of these tokens (sDAI, wstETH, and weETH) have available pools. Therefore, when any of the remaining tokens are deposited, they must first be converted into one of the three above (e.g., ETH -> stETH -> wstETH, ETH -> eETH -> weETH).

If the exchange rates of stETH/ETH and eETH/ETH deviate significantly from 1:1 during these conversions, the `_finalAmount` received may be more or less than expected. Although stETH and eETH generally track the value of ETH, there are situations where this approximately 1:1 conversion rate does not hold, [as seen in the past](https://dune.com/LidoAnalytical/Curve-ETHstETH)). As a result, users may receive fewer tokens than expected, leading to a loss of funds. Without an extra parameter to restrict `_finalAmount`, users cannot protect themselves from potential losses during the deposit process.

## Impact
On the scenario described above, users may receive fewer `_finalAmount` than expected, leading to a loss of funds during deposits.

## Code Snippet
deposit function
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L503-L515

ETH -> stETH conversion
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L808-L813

ETH -> eETH conversion
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L832-L835

## Tool used
Manual Review.

## Recommendation
To address this issue, it is recommended to add a `minFinalAmount` parameter in all the deposit functions. This will allow users to specify the minimum amount of `_finalAmount` tokens before `_deposit()`, thereby preventing the risk of unexpected losses during conversion.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because users can always optionally call deposit() by pre-converting DAI/sDAI, ETH/stETH, ETH/eTH at their control
