### ISSUE TITLE
Chuchulev - Missing storage gap variables in SophonFarmingState & Upgradeable2Step contracts necessary for later versions.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#86]
Chuchulev

medium

# Missing storage gap variables in SophonFarmingState & Upgradeable2Step contracts necessary for later versions.

## Summary
In upgradeable contracts, especially when using the proxy pattern, it's important to ensure that storage layouts between different versions of the contract are compatible. The contract does not currently implement storage gaps.

## Vulnerability Detail
`SophonFarmingState` & `Upgradeable2Step` contracts are missing a __gap[50] storage variable to allow for new storage variables in later versions.

## Impact
The lack of storage gaps in an upgradeable contract can lead to serious issues. If future upgrades add new state variables, the storage layout will be altered, potentially overwriting existing variables and causing the contract to behave unpredictably. The main vulnerability is storage collision, where new variables can overwrite existing ones, leading to incorrect data being read or written. This can compromise the contract's security and functionality.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/proxies/Upgradeable2Step.sol#L10-L39

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarmingState.sol#L18-L92

## Tool used
Manual Review

## Recommendation
To resolve this issue, it is recommended to include a __gap[50] storage variable in your upgradable contracts. This reserved space will ensure that any future upgrades can add new storage variables without affecting the layout of existing variables. 
```javascript
uint256[50] private __gap;
```
`uint256[50] private __gap;`: This array reserves 50 storage slots, allowing future versions of the contract to add new state variables without affecting the storage layout of existing variables.
By implementing storage gaps, you ensure that future upgrades can be made safely without risking storage collisions and maintaining the integrity of the contract's data. Please reference OpenZeppelin upgradeable contract templates.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because simple contracts with one of the parent contract not implementing storage gaps are considered low/informational
