### ISSUE TITLE
ECunha - Storage array variable can potentially lead to DoS, making many core functions in `SophonFarming.sol` not work

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#87]
ECunha

medium

# Storage array variable can potentially lead to DoS, making many core functions in `SophonFarming.sol` not work

## Summary

When dealing with arrays of unbounded size, the greater size of the array, the more gas will cost to append an element in it. If because of that the transaction ends up costing as much gas as the transaction gas limit, it will revert. 

## Vulnerability Detail

`SophonFarming::poolInfo` is an unbounded storage array, which can potentially grow indefinitely. The bigger in size an array gets, the more gas it will cost to append a new element in it. Therefore, `SophonFarming::poolInfo` can increase in size so that eventually the cost of calling a function that adds elements in it will be greater than the gas limit of a transaction, reverting it. This is called a Denial of Service attack.

<detail>
<summary>Proof of Code</summary>

Place the following test in `test/SophonFarming.t.sol` test file:

```javascript
function testDoS() public {
        uint256 allocPoint = 10;
        string memory description = "blabla";
        bool update = false;

        uint256 gasBefore = gasleft();

        console.log("adding 500 pools");

        uint120 amountOfPools = 500;
        vm.startPrank(deployer);
        for (uint160 i = 0; i < amountOfPools; ++i) {
            sophonFarming.add(allocPoint, address(i), description, update);
        }
        vm.stopPrank();

        uint256 gasAfter = gasleft();

        console.log("gas consumed (add):", gasBefore - gasAfter);

        gasBefore = gasleft();

        sophonFarming.getPoolInfo();

        gasAfter = gasleft();

        console.log("gas consumed (read):", gasBefore - gasAfter);

        console.log("adding 600 pools");

        gasBefore = gasleft();

        amountOfPools = 600;
        vm.startPrank(deployer);
        for (uint160 i = 500; i < 500 + amountOfPools; ++i) {
            sophonFarming.add(allocPoint, address(i), description, update);
        }
        vm.stopPrank();

        gasAfter = gasleft();

        console.log("gas consumed (add):", gasBefore - gasAfter);

        gasBefore = gasleft();

        sophonFarming.getPoolInfo();

        gasAfter = gasleft();

        console.log("gas consumed (read):", gasBefore - gasAfter);

        console.log("adding 600 pools");

        gasBefore = gasleft();

        amountOfPools = 600;
        vm.startPrank(deployer);
        for (uint160 i = 1100; i < 1100 + amountOfPools; ++i) {
            sophonFarming.add(allocPoint, address(i), description, update);
        }
        vm.stopPrank();

        gasAfter = gasleft();

        console.log("gas consumed (add):", gasBefore - gasAfter);

        gasBefore = gasleft();

        sophonFarming.getPoolInfo();

        gasAfter = gasleft();

        console.log("gas consumed (read):", gasBefore - gasAfter);
    }
```

Run it with `forge test --mt testDoS` and check the logs on the console. Something as follows should be shown on the terminal:
```shell
Logs:
  adding 500 pools
  gas consumed (add): 64006381
  gas consumed (read): 3115333
  adding 600 pools
  gas consumed (add): 76890395
  gas consumed (read): 10175988
  adding 600 pools
  gas consumed (add): 76954430
  gas consumed (read): 23359726
```

This proves that the gas will continuously increase, leading to a potential Denial of Service.

</detail>

## Impact

Most of the functions in `SophonFarming.sol` won't work, such as:
- `add`
- `massUpdatePools`
- `_pendingPoints`
- `getPoolInfo`
- `getOptimizedUserInfo`
- `getPendingPoints`

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L170-L182

## Tool used

Manual Review, Foundry

## Recommendation

Avoid using unbounded storage array variables, and use mappings instead. If arrays are really necessary, bound them.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the array length is controlled by the trusted admin/owner. Currently, there are only 3 elements in poolInfo
