### ISSUE TITLE
KupiaSec - When the `startBlock` is reset, the `lastRewardBlock`s of the pools are not updated accordingly

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#90]
KupiaSec

high

# When the `startBlock` is reset, the `lastRewardBlock`s of the pools are not updated accordingly

## Summary

The `SophonFarming.setStartBlock()` function resets the `startBlock` value, but does not update the `lastRewardBlock`s of the pools.

## Vulnerability Detail

When the `setStartBlock()` function is called, it only updates the `startBlock` value, but does not reset the `lastRewardBlock`s of the pools.

In the normal situation, the `lastRewardBlock`s of the pools are initialized to the `startBlock` value in the [add()](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L163) function. However, if the owner later resets the `startBlock` to a value smaller than the original one, the `lastRewardBlock`s will remain set to the previous, higher `startBlock` value.

As a result, when the first update of the pools is performed, the rewards will be miscalculated. The system will assume the point distribution started from the old, higher `startBlock` value, instead of the new, lower `startBlock` value. This is because the [blockMultiplier](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L423) is calculated based on the `lastRewardBlock`.

This mismatch in `startBlock` and `lastRewardBlock` values leads to an incorrect rewards calculation, resulting in a loss of points for the users.

## Impact

If the owner resets the `startBlock` to a value smaller than the previous one, users will lose a portion of their accumulated reward points.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L272-L280

## Tool used

Manual Review

## Recommendation

When the `setStartBlock()` function is called, the `lastRewardBlock`s of the pools should also be reset, in addition to the `startBlock`.

Duplicate of #108

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  valid because lastRewardBlock for each pool should indeed sync with the latest startBlock

**Comment by mystery0x** [comment]
This report should be valid as it described scenario 2 of https://github.com/sherlock-audit/2024-05-sophon-judging/issues/108.
