### ISSUE TITLE
KupiaSec - The `msg.sender` access control check in the `Upgradeable2Step.becomeImplementation()` function is not suitable for its intended purpose

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#91]
KupiaSec

medium

# The `msg.sender` access control check in the `Upgradeable2Step.becomeImplementation()` function is not suitable for its intended purpose

## Summary

The `becomeImplementation()` function expects the `msg.sender` to be the owner of the proxy contract passed as a parameter, not the owner of the contract itself. This access control mechanism does not align with the intended purpose of the `2step` upgrade process.

## Vulnerability Detail

For an `Upgradeable2Step` contract, the `becomeImplementation()` function must be called to accept becoming the new implementation for another proxy. However, the `msg.sender` in the `becomeImplementation()` function is expected to be the owner of the other proxy contract. This access control mechanism does not align with the intended purpose of the `2step` upgrade process.

```solidity
        if (msg.sender != proxy.owner()) {
            revert Unauthorized();
        }
```

## Impact

It is possible to modify the implementation without the new implementation contract's aggrement.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/proxies/Upgradeable2Step.sol#L33-L38

## Tool used

Manual Review

## Recommendation

Recommend to modify the `msg.sender` check in the `becomeImplementation()`.

```diff
    function becomeImplementation(Upgradeable2Step proxy) public {
-       if (msg.sender != proxy.owner()) {
+       if (msg.sender != owner()) {
            revert Unauthorized();
        }
        proxy.acceptImplementation();
    }
```

**Comment by sherlock-admin4** [comment]
2 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the logic will work as intended

**0xreadyplayer1** commented:
>  The watson incorrectly assumes that proxy B has a separate owner but the contest readme states `There is a single admin (owner) that is trusted`. However - the function is public and only allows the call to `becomeImplementation` to be successful if the caller is the owner of proxy A which is intened.
