### ISSUE TITLE
whitehair0330 - No modification of the `lastRewardBlock` in the `SophonFarming.setStartBlock()` function.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#98]
whitehair0330

high

# No modification of the `lastRewardBlock` in the `SophonFarming.setStartBlock()` function.

## Summary

When the owner resets the `startBlock`, they do not modify the `lastRewardBlock` of all the pools.

## Vulnerability Detail

The state variable `startBlock` was already set in the `initialize()` function, and the `lastRewardBlock`s of all pools were also set at that time. However, when the owner resets the `startBlock`, the `lastRewardBlock`s are not reset. 

```solidity
    function setStartBlock(uint256 _startBlock) public onlyOwner {
        if (_startBlock == 0 || (endBlock != 0 && _startBlock >= endBlock)) {
            revert InvalidStartBlock();
        }
        if (getBlockNumber() > startBlock) {
            revert FarmingIsStarted();
        }
        startBlock = _startBlock;
    }
```

Let's consider the following scenario:

1. The owner initializes the `startBlock` to `100` at the `50`th block. At that time, the `lastRewardBlock`s of all pools are set to `100`.
2. Next, the owner resets the `startBlock` to `150` at the `60`th block. The `lastRewardBlock`s of all pools remain at `100`.

In this case, at the first update after the farming started, the `accPointsPerShare` of the pools will be miscalculated. This is because the `blockMultiplier` is accounted from the `100`th block (the `lastRewardBlock`), not from the `150`th block (the real `startBlock`). It means that the point distribution had already started from the `100`th block, not from the `150`th block.

## Impact

Users may receive more points than they are entitled to.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L272-L280

## Tool used

Manual Review

## Recommendation

When the owner resets the `startBlock`, the `lastRewardBlock` of all the pools should also be modified accordingly.

Duplicate of #108

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  valid because lastRewardBlock for each pool should indeed sync with the latest startBlock

**Comment by mystery0x** [comment]
This report should be valid as it described scenario 1 of https://github.com/sherlock-audit/2024-05-sophon-judging/issues/108.
