### ISSUE TITLE
whitehair0330 - Incorrect caller check in the `Upgradeable2Step.becomeImplementation()` function.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#99]
whitehair0330

high

# Incorrect caller check in the `Upgradeable2Step.becomeImplementation()` function.

## Summary

The `becomeImplementation()` function should be called by the owner of the contract itself, not the owner of the parameter proxy.

## Vulnerability Detail

Let's follow the flow to reset the implementation:

1. The owner of Proxy A sets the `pendingImplementation` to the address of Proxy B by calling the `replaceImplementation()`.

```solidity
    function replaceImplementation(address impl_) public onlyOwner {
        pendingImplementation = impl_;
        emit ReplaceImplementationStarted(implementation, impl_);
    }
```

2. To actually reset the implementation to Proxy B, the `acceptImplementation()` function of Proxy A should be called by Proxy B. So, the owner of Proxy B calls Proxy B's `becomeImplementation()` function with Proxy A as the parameter.

```solidity
    function becomeImplementation(Upgradeable2Step proxy) public {
34     if (msg.sender != proxy.owner()) {
            revert Unauthorized();
        }
        proxy.acceptImplementation();
    }
```

However, as you can see at `L34`, the `becomeImplementation()` function requires the caller to be the owner of Proxy A. So, the transaction will be reverted since the caller is the owner of Proxy B.

## Impact

Changing the implementation is not possible.

## Code Snippet

https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/proxies/Upgradeable2Step.sol#L33-L38

## Tool used

Manual Review

## Recommendation

The `becomeImplementation()` function should be fixed as follows.

```diff
-   function becomeImplementation(Upgradeable2Step proxy) public {
-      if (msg.sender != proxy.owner()) {
-           revert Unauthorized();
-       }
+   function becomeImplementation(Upgradeable2Step proxy) public onlyOwner {
        proxy.acceptImplementation();
    }
```

**Comment by sherlock-admin3** [comment]
2 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because the logic will work as intended

**0xreadyplayer1** commented:
>  The watson incorrectly assumes that proxy B has a separate owner but the contest readme states `There is a single admin (owner) that is trusted`. However - the function is public and only allows the call to `becomeImplementation` to be successful if the caller is the owner of proxy A which is intened.
